///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RequestListPointViewPriceList {
/*
{
  "id": "03f0f511593447e4ac4846b579a4cc50",
  "price": 500000
} 
*/

  String? id;
  int? price;

  RequestListPointViewPriceList({
    this.id,
    this.price,
  });
  RequestListPointViewPriceList.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    price = json['price']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['price'] = price;
    return data;
  }
}

class RequestListPointView {
/*
{
  "price_list": [
    {
      "id": "03f0f511593447e4ac4846b579a4cc50",
      "price": 500000
    }
  ]
} 
*/

  List<RequestListPointViewPriceList?>? priceList;

  RequestListPointView({
    this.priceList,
  });
  RequestListPointView.fromJson(Map<String, dynamic> json) {
    if (json['price_list'] != null) {
      final v = json['price_list'];
      final arr0 = <RequestListPointViewPriceList>[];
      v.forEach((v) {
        arr0.add(RequestListPointViewPriceList.fromJson(v));
      });
      priceList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (priceList != null) {
      final v = priceList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['price_list'] = arr0;
    }
    return data;
  }
}
