///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RequestCheckoutHotelReceiverData {
/*
{
  "country_code": "84",
  "first_name": "Chiên",
  "last_name": "Bùi",
  "phone": "344850761"
}
*/

  String? countryCode;
  String? firstName;
  String? lastName;
  String? phone;

  RequestCheckoutHotelReceiverData({
    this.countryCode,
    this.firstName,
    this.lastName,
    this.phone,
  });
  RequestCheckoutHotelReceiverData.fromJson(Map<String, dynamic> json) {
    countryCode = json['country_code']?.toString();
    firstName = json['first_name']?.toString();
    lastName = json['last_name']?.toString();
    phone = json['phone']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country_code'] = countryCode;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['phone'] = phone;
    return data;
  }
}

class RequestCheckoutHotel {
/*
{
  "bed_type_group_id": 0,
  "receiver_data": [
    {
      "country_code": "84",
      "first_name": "Chiên",
      "last_name": "Bùi",
      "phone": "344850761"
    }
  ],
  "token_id": "d1ededee7e7541aa97593387c669eaaf"
}
*/

  int? bedTypeGroupId;
  List<RequestCheckoutHotelReceiverData?>? receiverData;
  String? tokenId;

  RequestCheckoutHotel({
    this.bedTypeGroupId,
    this.receiverData,
    this.tokenId,
  });
  RequestCheckoutHotel.fromJson(Map<String, dynamic> json) {
    bedTypeGroupId = json['bed_type_group_id']?.toInt();
    if (json['receiver_data'] != null) {
      final v = json['receiver_data'];
      final arr0 = <RequestCheckoutHotelReceiverData>[];
      v.forEach((v) {
        arr0.add(RequestCheckoutHotelReceiverData.fromJson(v));
      });
      receiverData = arr0;
    }
    tokenId = json['token_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bed_type_group_id'] = bedTypeGroupId;
    if (receiverData != null) {
      final v = receiverData;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['receiver_data'] = arr0;
    }
    data['token_id'] = tokenId;
    return data;
  }
}

class RequestCheckoutBookerData {
/*
{
  "email": "tan@gmail.com",
  "first_name": "Chiên",
  "gender": 2,
  "last_name": "Bùi",
  "phone": "344850761"
}
*/

  String? email;
  String? firstName;
  int? gender;
  String? lastName;
  String? phone;

  RequestCheckoutBookerData({
    this.email,
    this.firstName,
    this.gender,
    this.lastName,
    this.phone,
  });
  RequestCheckoutBookerData.fromJson(Map<String, dynamic> json) {
    email = json['email']?.toString();
    firstName = json['first_name']?.toString();
    gender = json['gender']?.toInt();
    lastName = json['last_name']?.toString();
    phone = json['phone']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['email'] = email;
    data['first_name'] = firstName;
    data['gender'] = gender;
    data['last_name'] = lastName;
    data['phone'] = phone;
    return data;
  }
}

class RequestCheckout {
/*
{
  "booker_data": {
    "email": "tan@gmail.com",
    "first_name": "Chiên",
    "gender": 2,
    "last_name": "Bùi",
    "phone": "344850761"
  },
  "hotel": {
    "bed_type_group_id": 0,
    "receiver_data": [
      {
        "country_code": "84",
        "first_name": "Chiên",
        "last_name": "Bùi",
        "phone": "344850761"
      }
    ],
    "token_id": "d1ededee7e7541aa97593387c669eaaf"
  },
  "request_from": "APP_ANDROID",
  "user_id": 436664
}
*/

  RequestCheckoutBookerData? bookerData;
  RequestCheckoutHotel? hotel;
  String? requestFrom;
  int? userId;

  RequestCheckout({
    this.bookerData,
    this.hotel,
    this.requestFrom,
    this.userId,
  });
  RequestCheckout.fromJson(Map<String, dynamic> json) {
    bookerData = (json['booker_data'] != null) ? RequestCheckoutBookerData.fromJson(json['booker_data']) : null;
    hotel = (json['hotel'] != null) ? RequestCheckoutHotel.fromJson(json['hotel']) : null;
    requestFrom = json['request_from']?.toString();
    userId = json['user_id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (bookerData != null) {
      data['booker_data'] = bookerData!.toJson();
    }
    if (hotel != null) {
      data['hotel'] = hotel!.toJson();
    }
    data['request_from'] = requestFrom;
    data['user_id'] = userId;
    return data;
  }
}
