///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ListPointValueDataThirdPartyPrograms {
/*
{
  "id": "44279aff-1c1f-4f95-a8ec-a77efc4a15ba",
  "program_name_en": "LotusMiles",
  "program_name_vi": "Bông Sen Vàng",
  "program_image": "20200316_503210_dark_paladin.jpg",
  "allow_reward_split": false,
  "program_description_en": "chương trình tích điểm bông sen vàng",
  "point_equivelance_unit": "VND",
  "pt_eqv_hotel_min": "20000",
  "is_third_party": true,
  "reward_unit": 2,
  "program_description_vi": "Chương trình tích điểm bông sen vàng",
  "program_url": "vntrip.vn",
  "program_faq_url": "vntrip.vn",
  "name_unit": "Miles",
  "name_unit_vi": "Dặm"
}
*/

  String? id;
  String? programNameEn;
  String? programNameVi;
  String? programImage;
  bool? allowRewardSplit;
  String? programDescriptionEn;
  String? pointEquivelanceUnit;
  String? ptEqvHotelMin;
  bool? isThirdParty;
  int? rewardUnit;
  String? programDescriptionVi;
  String? programUrl;
  String? programFaqUrl;
  String? nameUnit;
  String? nameUnitVi;

  ListPointValueDataThirdPartyPrograms({
    this.id,
    this.programNameEn,
    this.programNameVi,
    this.programImage,
    this.allowRewardSplit,
    this.programDescriptionEn,
    this.pointEquivelanceUnit,
    this.ptEqvHotelMin,
    this.isThirdParty,
    this.rewardUnit,
    this.programDescriptionVi,
    this.programUrl,
    this.programFaqUrl,
    this.nameUnit,
    this.nameUnitVi,
  });
  ListPointValueDataThirdPartyPrograms.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    programNameEn = json['program_name_en']?.toString();
    programNameVi = json['program_name_vi']?.toString();
    programImage = json['program_image']?.toString();
    allowRewardSplit = json['allow_reward_split'];
    programDescriptionEn = json['program_description_en']?.toString();
    pointEquivelanceUnit = json['point_equivelance_unit']?.toString();
    ptEqvHotelMin = json['pt_eqv_hotel_min']?.toString();
    isThirdParty = json['is_third_party'];
    rewardUnit = json['reward_unit']?.toInt();
    programDescriptionVi = json['program_description_vi']?.toString();
    programUrl = json['program_url']?.toString();
    programFaqUrl = json['program_faq_url']?.toString();
    nameUnit = json['name_unit']?.toString();
    nameUnitVi = json['name_unit_vi']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['program_name_en'] = programNameEn;
    data['program_name_vi'] = programNameVi;
    data['program_image'] = programImage;
    data['allow_reward_split'] = allowRewardSplit;
    data['program_description_en'] = programDescriptionEn;
    data['point_equivelance_unit'] = pointEquivelanceUnit;
    data['pt_eqv_hotel_min'] = ptEqvHotelMin;
    data['is_third_party'] = isThirdParty;
    data['reward_unit'] = rewardUnit;
    data['program_description_vi'] = programDescriptionVi;
    data['program_url'] = programUrl;
    data['program_faq_url'] = programFaqUrl;
    data['name_unit'] = nameUnit;
    data['name_unit_vi'] = nameUnitVi;
    return data;
  }
}

class ListPointValueDataLoyaltyProgram {
/*
{
  "id": "3e72fb2d-a2c6-4ec2-b6a7-0e19be9c2d80",
  "program_name_en": "Vntrip.vn Cashback",
  "program_name_vi": "Hoàn tiền Vntrip.vn",
  "is_third_party": false,
  "allow_reward_split": true,
  "program_description_en": "Vntrip.vn cashback program",
  "point_equivelance_unit": "PERCENT",
  "pt_eqv_hotel_min": "3",
  "percentage_split": 66,
  "program_image": "20180710_357390_Viplogo.png",
  "reward_unit": null,
  "program_description_vi": "Chương trình hoàn tiền Vntrip.vn",
  "program_url": "https://special.vntrip.vn/member",
  "program_faq_url": "https://special.vntrip.vn/member"
}
*/

  String? id;
  String? programNameEn;
  String? programNameVi;
  bool? isThirdParty;
  bool? allowRewardSplit;
  String? programDescriptionEn;
  String? pointEquivelanceUnit;
  String? ptEqvHotelMin;
  int? percentageSplit;
  String? programImage;
  String? rewardUnit;
  String? programDescriptionVi;
  String? programUrl;
  String? programFaqUrl;

  ListPointValueDataLoyaltyProgram({
    this.id,
    this.programNameEn,
    this.programNameVi,
    this.isThirdParty,
    this.allowRewardSplit,
    this.programDescriptionEn,
    this.pointEquivelanceUnit,
    this.ptEqvHotelMin,
    this.percentageSplit,
    this.programImage,
    this.rewardUnit,
    this.programDescriptionVi,
    this.programUrl,
    this.programFaqUrl,
  });
  ListPointValueDataLoyaltyProgram.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    programNameEn = json['program_name_en']?.toString();
    programNameVi = json['program_name_vi']?.toString();
    isThirdParty = json['is_third_party'];
    allowRewardSplit = json['allow_reward_split'];
    programDescriptionEn = json['program_description_en']?.toString();
    pointEquivelanceUnit = json['point_equivelance_unit']?.toString();
    ptEqvHotelMin = json['pt_eqv_hotel_min']?.toString();
    percentageSplit = json['percentage_split']?.toInt();
    programImage = json['program_image']?.toString();
    rewardUnit = json['reward_unit']?.toString();
    programDescriptionVi = json['program_description_vi']?.toString();
    programUrl = json['program_url']?.toString();
    programFaqUrl = json['program_faq_url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['program_name_en'] = programNameEn;
    data['program_name_vi'] = programNameVi;
    data['is_third_party'] = isThirdParty;
    data['allow_reward_split'] = allowRewardSplit;
    data['program_description_en'] = programDescriptionEn;
    data['point_equivelance_unit'] = pointEquivelanceUnit;
    data['pt_eqv_hotel_min'] = ptEqvHotelMin;
    data['percentage_split'] = percentageSplit;
    data['program_image'] = programImage;
    data['reward_unit'] = rewardUnit;
    data['program_description_vi'] = programDescriptionVi;
    data['program_url'] = programUrl;
    data['program_faq_url'] = programFaqUrl;
    return data;
  }
}

class ListPointValueDataPriceListThirdParty {
/*
{
  "id": "44279aff-1c1f-4f95-a8ec-a77efc4a15ba",
  "name": "LotusMiles",
  "name_vi": "Bông Sen Vàng",
  "description_en": "chương trình tích điểm bông sen vàng",
  "description_vi": "Chương trình tích điểm bông sen vàng",
  "point": 8,
  "program_image": "https://test-statics.vntrip.vn/uploads/loyalty_program/20200316_503210_dark_paladin.jpg",
  "name_unit": "Miles",
  "name_unit_vi": "Dặm",
  "program_url": "vntrip.vn",
  "program_faq_url": "vntrip.vn"
}
*/

  String? id;
  String? name;
  String? nameVi;
  String? descriptionEn;
  String? descriptionVi;
  int? point;
  String? programImage;
  String? nameUnit;
  String? nameUnitVi;
  String? programUrl;
  String? programFaqUrl;

  ListPointValueDataPriceListThirdParty({
    this.id,
    this.name,
    this.nameVi,
    this.descriptionEn,
    this.descriptionVi,
    this.point,
    this.programImage,
    this.nameUnit,
    this.nameUnitVi,
    this.programUrl,
    this.programFaqUrl,
  });
  ListPointValueDataPriceListThirdParty.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    nameVi = json['name_vi']?.toString();
    descriptionEn = json['description_en']?.toString();
    descriptionVi = json['description_vi']?.toString();
    point = json['point']?.toInt();
    programImage = json['program_image']?.toString();
    nameUnit = json['name_unit']?.toString();
    nameUnitVi = json['name_unit_vi']?.toString();
    programUrl = json['program_url']?.toString();
    programFaqUrl = json['program_faq_url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['name_vi'] = nameVi;
    data['description_en'] = descriptionEn;
    data['description_vi'] = descriptionVi;
    data['point'] = point;
    data['program_image'] = programImage;
    data['name_unit'] = nameUnit;
    data['name_unit_vi'] = nameUnitVi;
    data['program_url'] = programUrl;
    data['program_faq_url'] = programFaqUrl;
    return data;
  }
}

class ListPointValueDataPriceListLoyalty {
/*
{
  "id": "3e72fb2d-a2c6-4ec2-b6a7-0e19be9c2d80",
  "name": "Vntrip.vn Cashback",
  "name_vi": "Hoàn tiền Vntrip.vn",
  "description_en": "Vntrip.vn cashback program",
  "description_vi": "Chương trình hoàn tiền Vntrip.vn",
  "allow_reward_split": true,
  "point": 15000,
  "point_split": 9900,
  "program_image": "https://test-statics.vntrip.vn/uploads/loyalty_program/20180710_357390_Viplogo.png",
  "program_url": "https://special.vntrip.vn/member",
  "program_faq_url": "https://special.vntrip.vn/member"
}
*/

  String? id;
  String? name;
  String? nameVi;
  String? descriptionEn;
  String? descriptionVi;
  bool? allowRewardSplit;
  int? point;
  int? pointSplit;
  String? programImage;
  String? programUrl;
  String? programFaqUrl;

  ListPointValueDataPriceListLoyalty({
    this.id,
    this.name,
    this.nameVi,
    this.descriptionEn,
    this.descriptionVi,
    this.allowRewardSplit,
    this.point,
    this.pointSplit,
    this.programImage,
    this.programUrl,
    this.programFaqUrl,
  });
  ListPointValueDataPriceListLoyalty.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    nameVi = json['name_vi']?.toString();
    descriptionEn = json['description_en']?.toString();
    descriptionVi = json['description_vi']?.toString();
    allowRewardSplit = json['allow_reward_split'];
    point = json['point']?.toInt();
    pointSplit = json['point_split']?.toInt();
    programImage = json['program_image']?.toString();
    programUrl = json['program_url']?.toString();
    programFaqUrl = json['program_faq_url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['name_vi'] = nameVi;
    data['description_en'] = descriptionEn;
    data['description_vi'] = descriptionVi;
    data['allow_reward_split'] = allowRewardSplit;
    data['point'] = point;
    data['point_split'] = pointSplit;
    data['program_image'] = programImage;
    data['program_url'] = programUrl;
    data['program_faq_url'] = programFaqUrl;
    return data;
  }
}

class ListPointValueDataPriceList {
/*
{
  "id": "03f0f511593447e4ac4846b579a4cc50",
  "price": 500000,
  "loyalty": {
    "id": "3e72fb2d-a2c6-4ec2-b6a7-0e19be9c2d80",
    "name": "Vntrip.vn Cashback",
    "name_vi": "Hoàn tiền Vntrip.vn",
    "description_en": "Vntrip.vn cashback program",
    "description_vi": "Chương trình hoàn tiền Vntrip.vn",
    "allow_reward_split": true,
    "point": 15000,
    "point_split": 9900,
    "program_image": "https://test-statics.vntrip.vn/uploads/loyalty_program/20180710_357390_Viplogo.png",
    "program_url": "https://special.vntrip.vn/member",
    "program_faq_url": "https://special.vntrip.vn/member"
  },
  "third_party": [
    {
      "id": "44279aff-1c1f-4f95-a8ec-a77efc4a15ba",
      "name": "LotusMiles",
      "name_vi": "Bông Sen Vàng",
      "description_en": "chương trình tích điểm bông sen vàng",
      "description_vi": "Chương trình tích điểm bông sen vàng",
      "point": 8,
      "program_image": "https://test-statics.vntrip.vn/uploads/loyalty_program/20200316_503210_dark_paladin.jpg",
      "name_unit": "Miles",
      "name_unit_vi": "Dặm",
      "program_url": "vntrip.vn",
      "program_faq_url": "vntrip.vn"
    }
  ]
}
*/

  String? id;
  int? price;
  ListPointValueDataPriceListLoyalty? loyalty;
  List<ListPointValueDataPriceListThirdParty?>? thirdParty;

  ListPointValueDataPriceList({
    this.id,
    this.price,
    this.loyalty,
    this.thirdParty,
  });
  ListPointValueDataPriceList.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    price = json['price']?.toInt();
    loyalty = (json['loyalty'] != null) ? ListPointValueDataPriceListLoyalty.fromJson(json['loyalty']) : null;
    if (json['third_party'] != null) {
      final v = json['third_party'];
      final arr0 = <ListPointValueDataPriceListThirdParty>[];
      v.forEach((v) {
        arr0.add(ListPointValueDataPriceListThirdParty.fromJson(v));
      });
      thirdParty = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['price'] = price;
    if (loyalty != null) {
      data['loyalty'] = loyalty!.toJson();
    }
    if (thirdParty != null) {
      final v = thirdParty;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['third_party'] = arr0;
    }
    return data;
  }
}

class ListPointValueData {
/*
{
  "price_list": [
    {
      "id": "03f0f511593447e4ac4846b579a4cc50",
      "price": 500000,
      "loyalty": {
        "id": "3e72fb2d-a2c6-4ec2-b6a7-0e19be9c2d80",
        "name": "Vntrip.vn Cashback",
        "name_vi": "Hoàn tiền Vntrip.vn",
        "description_en": "Vntrip.vn cashback program",
        "description_vi": "Chương trình hoàn tiền Vntrip.vn",
        "allow_reward_split": true,
        "point": 15000,
        "point_split": 9900,
        "program_image": "https://test-statics.vntrip.vn/uploads/loyalty_program/20180710_357390_Viplogo.png",
        "program_url": "https://special.vntrip.vn/member",
        "program_faq_url": "https://special.vntrip.vn/member"
      },
      "third_party": [
        {
          "id": "44279aff-1c1f-4f95-a8ec-a77efc4a15ba",
          "name": "LotusMiles",
          "name_vi": "Bông Sen Vàng",
          "description_en": "chương trình tích điểm bông sen vàng",
          "description_vi": "Chương trình tích điểm bông sen vàng",
          "point": 8,
          "program_image": "https://test-statics.vntrip.vn/uploads/loyalty_program/20200316_503210_dark_paladin.jpg",
          "name_unit": "Miles",
          "name_unit_vi": "Dặm",
          "program_url": "vntrip.vn",
          "program_faq_url": "vntrip.vn"
        }
      ]
    }
  ],
  "loyalty_program": [
    {
      "id": "3e72fb2d-a2c6-4ec2-b6a7-0e19be9c2d80",
      "program_name_en": "Vntrip.vn Cashback",
      "program_name_vi": "Hoàn tiền Vntrip.vn",
      "is_third_party": false,
      "allow_reward_split": true,
      "program_description_en": "Vntrip.vn cashback program",
      "point_equivelance_unit": "PERCENT",
      "pt_eqv_hotel_min": "3",
      "percentage_split": 66,
      "program_image": "20180710_357390_Viplogo.png",
      "reward_unit": null,
      "program_description_vi": "Chương trình hoàn tiền Vntrip.vn",
      "program_url": "https://special.vntrip.vn/member",
      "program_faq_url": "https://special.vntrip.vn/member"
    }
  ],
  "third_party_Programs": [
    {
      "id": "44279aff-1c1f-4f95-a8ec-a77efc4a15ba",
      "program_name_en": "LotusMiles",
      "program_name_vi": "Bông Sen Vàng",
      "program_image": "20200316_503210_dark_paladin.jpg",
      "allow_reward_split": false,
      "program_description_en": "chương trình tích điểm bông sen vàng",
      "point_equivelance_unit": "VND",
      "pt_eqv_hotel_min": "20000",
      "is_third_party": true,
      "reward_unit": 2,
      "program_description_vi": "Chương trình tích điểm bông sen vàng",
      "program_url": "vntrip.vn",
      "program_faq_url": "vntrip.vn",
      "name_unit": "Miles",
      "name_unit_vi": "Dặm"
    }
  ],
  "user_point_equivalent_rate": 3
}
*/

  List<ListPointValueDataPriceList?>? priceList;
  List<ListPointValueDataLoyaltyProgram?>? loyaltyProgram;
  List<ListPointValueDataThirdPartyPrograms?>? thirdPartyPrograms;
  int? userPointEquivalentRate;

  ListPointValueData({
    this.priceList,
    this.loyaltyProgram,
    this.thirdPartyPrograms,
    this.userPointEquivalentRate,
  });
  ListPointValueData.fromJson(Map<String, dynamic> json) {
    if (json['price_list'] != null) {
      final v = json['price_list'];
      final arr0 = <ListPointValueDataPriceList>[];
      v.forEach((v) {
        arr0.add(ListPointValueDataPriceList.fromJson(v));
      });
      priceList = arr0;
    }
    if (json['loyalty_program'] != null) {
      final v = json['loyalty_program'];
      final arr0 = <ListPointValueDataLoyaltyProgram>[];
      v.forEach((v) {
        arr0.add(ListPointValueDataLoyaltyProgram.fromJson(v));
      });
      loyaltyProgram = arr0;
    }
    if (json['third_party_Programs'] != null) {
      final v = json['third_party_Programs'];
      final arr0 = <ListPointValueDataThirdPartyPrograms>[];
      v.forEach((v) {
        arr0.add(ListPointValueDataThirdPartyPrograms.fromJson(v));
      });
      thirdPartyPrograms = arr0;
    }
    userPointEquivalentRate = json['user_point_equivalent_rate']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (priceList != null) {
      final v = priceList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['price_list'] = arr0;
    }
    if (loyaltyProgram != null) {
      final v = loyaltyProgram;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['loyalty_program'] = arr0;
    }
    if (thirdPartyPrograms != null) {
      final v = thirdPartyPrograms;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['third_party_Programs'] = arr0;
    }
    data['user_point_equivalent_rate'] = userPointEquivalentRate;
    return data;
  }
}

class ListPointValue {
/*
{
  "status": "success",
  "message": "Success",
  "data": {
    "price_list": [
      {
        "id": "03f0f511593447e4ac4846b579a4cc50",
        "price": 500000,
        "loyalty": {
          "id": "3e72fb2d-a2c6-4ec2-b6a7-0e19be9c2d80",
          "name": "Vntrip.vn Cashback",
          "name_vi": "Hoàn tiền Vntrip.vn",
          "description_en": "Vntrip.vn cashback program",
          "description_vi": "Chương trình hoàn tiền Vntrip.vn",
          "allow_reward_split": true,
          "point": 15000,
          "point_split": 9900,
          "program_image": "https://test-statics.vntrip.vn/uploads/loyalty_program/20180710_357390_Viplogo.png",
          "program_url": "https://special.vntrip.vn/member",
          "program_faq_url": "https://special.vntrip.vn/member"
        },
        "third_party": [
          {
            "id": "44279aff-1c1f-4f95-a8ec-a77efc4a15ba",
            "name": "LotusMiles",
            "name_vi": "Bông Sen Vàng",
            "description_en": "chương trình tích điểm bông sen vàng",
            "description_vi": "Chương trình tích điểm bông sen vàng",
            "point": 8,
            "program_image": "https://test-statics.vntrip.vn/uploads/loyalty_program/20200316_503210_dark_paladin.jpg",
            "name_unit": "Miles",
            "name_unit_vi": "Dặm",
            "program_url": "vntrip.vn",
            "program_faq_url": "vntrip.vn"
          }
        ]
      }
    ],
    "loyalty_program": [
      {
        "id": "3e72fb2d-a2c6-4ec2-b6a7-0e19be9c2d80",
        "program_name_en": "Vntrip.vn Cashback",
        "program_name_vi": "Hoàn tiền Vntrip.vn",
        "is_third_party": false,
        "allow_reward_split": true,
        "program_description_en": "Vntrip.vn cashback program",
        "point_equivelance_unit": "PERCENT",
        "pt_eqv_hotel_min": "3",
        "percentage_split": 66,
        "program_image": "20180710_357390_Viplogo.png",
        "reward_unit": null,
        "program_description_vi": "Chương trình hoàn tiền Vntrip.vn",
        "program_url": "https://special.vntrip.vn/member",
        "program_faq_url": "https://special.vntrip.vn/member"
      }
    ],
    "third_party_Programs": [
      {
        "id": "44279aff-1c1f-4f95-a8ec-a77efc4a15ba",
        "program_name_en": "LotusMiles",
        "program_name_vi": "Bông Sen Vàng",
        "program_image": "20200316_503210_dark_paladin.jpg",
        "allow_reward_split": false,
        "program_description_en": "chương trình tích điểm bông sen vàng",
        "point_equivelance_unit": "VND",
        "pt_eqv_hotel_min": "20000",
        "is_third_party": true,
        "reward_unit": 2,
        "program_description_vi": "Chương trình tích điểm bông sen vàng",
        "program_url": "vntrip.vn",
        "program_faq_url": "vntrip.vn",
        "name_unit": "Miles",
        "name_unit_vi": "Dặm"
      }
    ],
    "user_point_equivalent_rate": 3
  }
}
*/

  String? status;
  String? message;
  ListPointValueData? data;

  ListPointValue({
    this.status,
    this.message,
    this.data,
  });
  ListPointValue.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    message = json['message']?.toString();
    data = (json['data'] != null) ? ListPointValueData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
