///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ResponseSearchedRoomExtDataCountByType {
/*
{
  "count": 16,
  "type": "hotel"
}
*/

  int? count;
  String? type;

  ResponseSearchedRoomExtDataCountByType({
    this.count,
    this.type,
  });
  ResponseSearchedRoomExtDataCountByType.fromJson(Map<String, dynamic> json) {
    count = json['count']?.toInt();
    type = json['type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['count'] = count;
    data['type'] = type;
    return data;
  }
}

class ResponseSearchedRoomExtDataCountByProvinces {
/*
{
  "count": 16
}
*/

  int? count;

  ResponseSearchedRoomExtDataCountByProvinces({
    this.count,
  });
  ResponseSearchedRoomExtDataCountByProvinces.fromJson(Map<String, dynamic> json) {
    count = json['count']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['count'] = count;
    return data;
  }
}

class ResponseSearchedRoomExtDataCountByCities {
/*
{
  "count": 3,
  "seo_url": "ha-noi/ba-dinh",
  "province_id": 66,
  "city_seo_url": "ba-dinh",
  "name": "Quận Ba Đình",
  "id": 711,
  "province_code": "ha-noi",
  "province_name": "Hà Nội"
}
*/

  int? count;
  String? seoUrl;
  int? provinceId;
  String? citySeoUrl;
  String? name;
  int? id;
  String? provinceCode;
  String? provinceName;

  ResponseSearchedRoomExtDataCountByCities({
    this.count,
    this.seoUrl,
    this.provinceId,
    this.citySeoUrl,
    this.name,
    this.id,
    this.provinceCode,
    this.provinceName,
  });
  ResponseSearchedRoomExtDataCountByCities.fromJson(Map<String, dynamic> json) {
    count = json['count']?.toInt();
    seoUrl = json['seo_url']?.toString();
    provinceId = json['province_id']?.toInt();
    citySeoUrl = json['city_seo_url']?.toString();
    name = json['name']?.toString();
    id = json['id']?.toInt();
    provinceCode = json['province_code']?.toString();
    provinceName = json['province_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['count'] = count;
    data['seo_url'] = seoUrl;
    data['province_id'] = provinceId;
    data['city_seo_url'] = citySeoUrl;
    data['name'] = name;
    data['id'] = id;
    data['province_code'] = provinceCode;
    data['province_name'] = provinceName;
    return data;
  }
}

class ResponseSearchedRoomExtDataCountByFacilities {
/*
{
  "seo_code": "ho-boi",
  "name": "Hồ bơi",
  "id": 1,
  "count": 1
}
*/

  String? seoCode;
  String? name;
  int? id;
  int? count;

  ResponseSearchedRoomExtDataCountByFacilities({
    this.seoCode,
    this.name,
    this.id,
    this.count,
  });
  ResponseSearchedRoomExtDataCountByFacilities.fromJson(Map<String, dynamic> json) {
    seoCode = json['seo_code']?.toString();
    name = json['name']?.toString();
    id = json['id']?.toInt();
    count = json['count']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['seo_code'] = seoCode;
    data['name'] = name;
    data['id'] = id;
    data['count'] = count;
    return data;
  }
}

class ResponseSearchedRoomExtDataCountByArea {
/*
{
  "seo_code": "pho-co-ha-noi",
  "name": "Phố cổ Hà Nội",
  "id": 1,
  "count": 2
}
*/

  String? seoCode;
  String? name;
  int? id;
  int? count;

  ResponseSearchedRoomExtDataCountByArea({
    this.seoCode,
    this.name,
    this.id,
    this.count,
  });
  ResponseSearchedRoomExtDataCountByArea.fromJson(Map<String, dynamic> json) {
    seoCode = json['seo_code']?.toString();
    name = json['name']?.toString();
    id = json['id']?.toInt();
    count = json['count']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['seo_code'] = seoCode;
    data['name'] = name;
    data['id'] = id;
    data['count'] = count;
    return data;
  }
}

class ResponseSearchedRoomExtDataCountByStar {
/*
{
  "no_star": 2,
  "one_star": 1,
  "two_star": 4,
  "three_star": 5,
  "four_star": 2,
  "five_star": 2
}
*/

  int? noStar;
  int? oneStar;
  int? twoStar;
  int? threeStar;
  int? fourStar;
  int? fiveStar;

  ResponseSearchedRoomExtDataCountByStar({
    this.noStar,
    this.oneStar,
    this.twoStar,
    this.threeStar,
    this.fourStar,
    this.fiveStar,
  });
  ResponseSearchedRoomExtDataCountByStar.fromJson(Map<String, dynamic> json) {
    noStar = json['no_star']?.toInt();
    oneStar = json['one_star']?.toInt();
    twoStar = json['two_star']?.toInt();
    threeStar = json['three_star']?.toInt();
    fourStar = json['four_star']?.toInt();
    fiveStar = json['five_star']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['no_star'] = noStar;
    data['one_star'] = oneStar;
    data['two_star'] = twoStar;
    data['three_star'] = threeStar;
    data['four_star'] = fourStar;
    data['five_star'] = fiveStar;
    return data;
  }
}

class ResponseSearchedRoomExtDataCountByPriceRange {
/*
{
  "below_500k": 3,
  "from_500k_to_1m": 12,
  "from_1m_to_2m": 1,
  "from_2m_to_5m": 0,
  "more_than_5m": 0
}
*/

  int? below_500k;
  int? from_500kTo_1m;
  int? from_1mTo_2m;
  int? from_2mTo_5m;
  int? moreThan_5m;

  ResponseSearchedRoomExtDataCountByPriceRange({
    this.below_500k,
    this.from_500kTo_1m,
    this.from_1mTo_2m,
    this.from_2mTo_5m,
    this.moreThan_5m,
  });
  ResponseSearchedRoomExtDataCountByPriceRange.fromJson(Map<String, dynamic> json) {
    below_500k = json['below_500k']?.toInt();
    from_500kTo_1m = json['from_500k_to_1m']?.toInt();
    from_1mTo_2m = json['from_1m_to_2m']?.toInt();
    from_2mTo_5m = json['from_2m_to_5m']?.toInt();
    moreThan_5m = json['more_than_5m']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['below_500k'] = below_500k;
    data['from_500k_to_1m'] = from_500kTo_1m;
    data['from_1m_to_2m'] = from_1mTo_2m;
    data['from_2m_to_5m'] = from_2mTo_5m;
    data['more_than_5m'] = moreThan_5m;
    return data;
  }
}

class ResponseSearchedRoomExtDataLocationInfo {
/*
{
  "province_id": 66,
  "province_name": "Hà Nội",
  "full_addr": "Hà Nội"
}
*/

  int? provinceId;
  String? provinceName;
  String? fullAddr;

  ResponseSearchedRoomExtDataLocationInfo({
    this.provinceId,
    this.provinceName,
    this.fullAddr,
  });
  ResponseSearchedRoomExtDataLocationInfo.fromJson(Map<String, dynamic> json) {
    provinceId = json['province_id']?.toInt();
    provinceName = json['province_name']?.toString();
    fullAddr = json['full_addr']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['province_id'] = provinceId;
    data['province_name'] = provinceName;
    data['full_addr'] = fullAddr;
    return data;
  }
}

class ResponseSearchedRoomExtData {
/*
{
  "location_info": {
    "province_id": 66,
    "province_name": "Hà Nội",
    "full_addr": "Hà Nội"
  },
  "count_by_price_range": {
    "below_500k": 3,
    "from_500k_to_1m": 12,
    "from_1m_to_2m": 1,
    "from_2m_to_5m": 0,
    "more_than_5m": 0
  },
  "count_by_star": {
    "no_star": 2,
    "one_star": 1,
    "two_star": 4,
    "three_star": 5,
    "four_star": 2,
    "five_star": 2
  },
  "count_by_area": [
    {
      "seo_code": "pho-co-ha-noi",
      "name": "Phố cổ Hà Nội",
      "id": 1,
      "count": 2
    }
  ],
  "count_by_facilities": [
    {
      "seo_code": "ho-boi",
      "name": "Hồ bơi",
      "id": 1,
      "count": 1
    }
  ],
  "count_by_cities": [
    {
      "count": 3,
      "seo_url": "ha-noi/ba-dinh",
      "province_id": 66,
      "city_seo_url": "ba-dinh",
      "name": "Quận Ba Đình",
      "id": 711,
      "province_code": "ha-noi",
      "province_name": "Hà Nội"
    }
  ],
  "count_by_provinces": [
    {
      "count": 16
    }
  ],
  "count_by_type": [
    {
      "count": 16,
      "type": "hotel"
    }
  ],
  "default_location": 0,
  "min_price_all": 80100,
  "max_price_all": 1200000,
  "median_price": 557500
}
*/

  ResponseSearchedRoomExtDataLocationInfo? locationInfo;
  ResponseSearchedRoomExtDataCountByPriceRange? countByPriceRange;
  ResponseSearchedRoomExtDataCountByStar? countByStar;
  List<ResponseSearchedRoomExtDataCountByArea?>? countByArea;
  List<ResponseSearchedRoomExtDataCountByFacilities?>? countByFacilities;
  List<ResponseSearchedRoomExtDataCountByCities?>? countByCities;
  List<ResponseSearchedRoomExtDataCountByProvinces?>? countByProvinces;
  List<ResponseSearchedRoomExtDataCountByType?>? countByType;
  int? defaultLocation;
  int? minPriceAll;
  int? maxPriceAll;
  int? medianPrice;

  ResponseSearchedRoomExtData({
    this.locationInfo,
    this.countByPriceRange,
    this.countByStar,
    this.countByArea,
    this.countByFacilities,
    this.countByCities,
    this.countByProvinces,
    this.countByType,
    this.defaultLocation,
    this.minPriceAll,
    this.maxPriceAll,
    this.medianPrice,
  });
  ResponseSearchedRoomExtData.fromJson(Map<String, dynamic> json) {
    locationInfo = (json['location_info'] != null) ? ResponseSearchedRoomExtDataLocationInfo.fromJson(json['location_info']) : null;
    countByPriceRange = (json['count_by_price_range'] != null) ? ResponseSearchedRoomExtDataCountByPriceRange.fromJson(json['count_by_price_range']) : null;
    countByStar = (json['count_by_star'] != null) ? ResponseSearchedRoomExtDataCountByStar.fromJson(json['count_by_star']) : null;
    if (json['count_by_area'] != null) {
      final v = json['count_by_area'];
      final arr0 = <ResponseSearchedRoomExtDataCountByArea>[];
      v.forEach((v) {
        arr0.add(ResponseSearchedRoomExtDataCountByArea.fromJson(v));
      });
      countByArea = arr0;
    }
    if (json['count_by_facilities'] != null) {
      final v = json['count_by_facilities'];
      final arr0 = <ResponseSearchedRoomExtDataCountByFacilities>[];
      v.forEach((v) {
        arr0.add(ResponseSearchedRoomExtDataCountByFacilities.fromJson(v));
      });
      countByFacilities = arr0;
    }
    if (json['count_by_cities'] != null) {
      final v = json['count_by_cities'];
      final arr0 = <ResponseSearchedRoomExtDataCountByCities>[];
      v.forEach((v) {
        arr0.add(ResponseSearchedRoomExtDataCountByCities.fromJson(v));
      });
      countByCities = arr0;
    }
    if (json['count_by_provinces'] != null) {
      final v = json['count_by_provinces'];
      final arr0 = <ResponseSearchedRoomExtDataCountByProvinces>[];
      v.forEach((v) {
        arr0.add(ResponseSearchedRoomExtDataCountByProvinces.fromJson(v));
      });
      countByProvinces = arr0;
    }
    if (json['count_by_type'] != null) {
      final v = json['count_by_type'];
      final arr0 = <ResponseSearchedRoomExtDataCountByType>[];
      v.forEach((v) {
        arr0.add(ResponseSearchedRoomExtDataCountByType.fromJson(v));
      });
      countByType = arr0;
    }
    defaultLocation = json['default_location']?.toInt();
    minPriceAll = json['min_price_all']?.toInt();
    maxPriceAll = json['max_price_all']?.toInt();
    medianPrice = json['median_price']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (locationInfo != null) {
      data['location_info'] = locationInfo!.toJson();
    }
    if (countByPriceRange != null) {
      data['count_by_price_range'] = countByPriceRange!.toJson();
    }
    if (countByStar != null) {
      data['count_by_star'] = countByStar!.toJson();
    }
    if (countByArea != null) {
      final v = countByArea;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['count_by_area'] = arr0;
    }
    if (countByFacilities != null) {
      final v = countByFacilities;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['count_by_facilities'] = arr0;
    }
    if (countByCities != null) {
      final v = countByCities;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['count_by_cities'] = arr0;
    }
    if (countByProvinces != null) {
      final v = countByProvinces;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['count_by_provinces'] = arr0;
    }
    if (countByType != null) {
      final v = countByType;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['count_by_type'] = arr0;
    }
    data['default_location'] = defaultLocation;
    data['min_price_all'] = minPriceAll;
    data['max_price_all'] = maxPriceAll;
    data['median_price'] = medianPrice;
    return data;
  }
}

class ResponseSearchedRoomDataShowPricesFinalPrice {
/*
{
  "title": "Giá cuối",
  "discount_type": "PERCENT",
  "incl_discount_value": 0,
  "excl_discount_value": 0,
  "incl_vat_fee_price": 360000,
  "excl_vat_fee_price": 342000,
  "order": 6,
  "show": false
}
*/

  String? title;
  String? discountType;
  int? inclDiscountValue;
  int? exclDiscountValue;
  int? inclVatFeePrice;
  int? exclVatFeePrice;
  int? order;
  bool? theShow;

  ResponseSearchedRoomDataShowPricesFinalPrice({
    this.title,
    this.discountType,
    this.inclDiscountValue,
    this.exclDiscountValue,
    this.inclVatFeePrice,
    this.exclVatFeePrice,
    this.order,
    this.theShow,
  });
  ResponseSearchedRoomDataShowPricesFinalPrice.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    discountType = json['discount_type']?.toString();
    inclDiscountValue = json['incl_discount_value']?.toInt();
    exclDiscountValue = json['excl_discount_value']?.toInt();
    inclVatFeePrice = json['incl_vat_fee_price']?.toInt();
    exclVatFeePrice = json['excl_vat_fee_price']?.toInt();
    order = json['order']?.toInt();
    theShow = json['show'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['discount_type'] = discountType;
    data['incl_discount_value'] = inclDiscountValue;
    data['excl_discount_value'] = exclDiscountValue;
    data['incl_vat_fee_price'] = inclVatFeePrice;
    data['excl_vat_fee_price'] = exclVatFeePrice;
    data['order'] = order;
    data['show'] = theShow;
    return data;
  }
}

class ResponseSearchedRoomDataShowPricesDiscountCoupon {
/*
{
  "title": "",
  "discount_type": "",
  "discount_value": "",
  "incl_vat_fee_price": 0,
  "excl_vat_fee_price": 0,
  "order": 5,
  "show": false
}
*/

  String? title;
  String? discountType;
  String? discountValue;
  int? inclVatFeePrice;
  int? exclVatFeePrice;
  int? order;
  bool? theShow;

  ResponseSearchedRoomDataShowPricesDiscountCoupon({
    this.title,
    this.discountType,
    this.discountValue,
    this.inclVatFeePrice,
    this.exclVatFeePrice,
    this.order,
    this.theShow,
  });
  ResponseSearchedRoomDataShowPricesDiscountCoupon.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    discountType = json['discount_type']?.toString();
    discountValue = json['discount_value']?.toString();
    inclVatFeePrice = json['incl_vat_fee_price']?.toInt();
    exclVatFeePrice = json['excl_vat_fee_price']?.toInt();
    order = json['order']?.toInt();
    theShow = json['show'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['discount_type'] = discountType;
    data['discount_value'] = discountValue;
    data['incl_vat_fee_price'] = inclVatFeePrice;
    data['excl_vat_fee_price'] = exclVatFeePrice;
    data['order'] = order;
    data['show'] = theShow;
    return data;
  }
}

class ResponseSearchedRoomDataShowPricesLoyaltyDiscount {
/*
{
  "title": "",
  "discount_type": "",
  "discount_value": "",
  "incl_vat_fee_price": 0,
  "excl_vat_fee_price": 0,
  "order": 4,
  "show": false
}
*/

  String? title;
  String? discountType;
  String? discountValue;
  int? inclVatFeePrice;
  int? exclVatFeePrice;
  int? order;
  bool? theShow;

  ResponseSearchedRoomDataShowPricesLoyaltyDiscount({
    this.title,
    this.discountType,
    this.discountValue,
    this.inclVatFeePrice,
    this.exclVatFeePrice,
    this.order,
    this.theShow,
  });
  ResponseSearchedRoomDataShowPricesLoyaltyDiscount.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    discountType = json['discount_type']?.toString();
    discountValue = json['discount_value']?.toString();
    inclVatFeePrice = json['incl_vat_fee_price']?.toInt();
    exclVatFeePrice = json['excl_vat_fee_price']?.toInt();
    order = json['order']?.toInt();
    theShow = json['show'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['discount_type'] = discountType;
    data['discount_value'] = discountValue;
    data['incl_vat_fee_price'] = inclVatFeePrice;
    data['excl_vat_fee_price'] = exclVatFeePrice;
    data['order'] = order;
    data['show'] = theShow;
    return data;
  }
}

class ResponseSearchedRoomDataShowPricesMobileRate {
/*
{
  "title": "MOBILE_RATE",
  "discount_type": "",
  "discount_value": "",
  "incl_vat_fee_price": 0,
  "excl_vat_fee_price": 0,
  "order": 3,
  "show": false
}
*/

  String? title;
  String? discountType;
  String? discountValue;
  int? inclVatFeePrice;
  int? exclVatFeePrice;
  int? order;
  bool? theShow;

  ResponseSearchedRoomDataShowPricesMobileRate({
    this.title,
    this.discountType,
    this.discountValue,
    this.inclVatFeePrice,
    this.exclVatFeePrice,
    this.order,
    this.theShow,
  });
  ResponseSearchedRoomDataShowPricesMobileRate.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    discountType = json['discount_type']?.toString();
    discountValue = json['discount_value']?.toString();
    inclVatFeePrice = json['incl_vat_fee_price']?.toInt();
    exclVatFeePrice = json['excl_vat_fee_price']?.toInt();
    order = json['order']?.toInt();
    theShow = json['show'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['discount_type'] = discountType;
    data['discount_value'] = discountValue;
    data['incl_vat_fee_price'] = inclVatFeePrice;
    data['excl_vat_fee_price'] = exclVatFeePrice;
    data['order'] = order;
    data['show'] = theShow;
    return data;
  }
}

class ResponseSearchedRoomDataShowPricesMemberDiscount {
/*
{
  "title": "SECRET_DEALS",
  "discount_type": "",
  "discount_value": "",
  "incl_vat_fee_price": 0,
  "excl_vat_fee_price": 0,
  "order": 2,
  "show": false
}
*/

  String? title;
  String? discountType;
  String? discountValue;
  int? inclVatFeePrice;
  int? exclVatFeePrice;
  int? order;
  bool? theShow;

  ResponseSearchedRoomDataShowPricesMemberDiscount({
    this.title,
    this.discountType,
    this.discountValue,
    this.inclVatFeePrice,
    this.exclVatFeePrice,
    this.order,
    this.theShow,
  });
  ResponseSearchedRoomDataShowPricesMemberDiscount.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    discountType = json['discount_type']?.toString();
    discountValue = json['discount_value']?.toString();
    inclVatFeePrice = json['incl_vat_fee_price']?.toInt();
    exclVatFeePrice = json['excl_vat_fee_price']?.toInt();
    order = json['order']?.toInt();
    theShow = json['show'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['discount_type'] = discountType;
    data['discount_value'] = discountValue;
    data['incl_vat_fee_price'] = inclVatFeePrice;
    data['excl_vat_fee_price'] = exclVatFeePrice;
    data['order'] = order;
    data['show'] = theShow;
    return data;
  }
}

class ResponseSearchedRoomDataShowPricesPromotion {
/*
{
  "title": "",
  "discount_type": "",
  "discount_value": "",
  "incl_vat_fee_price": 0,
  "excl_vat_fee_price": 0,
  "order": 1,
  "end_time": -1,
  "show": false
}
*/

  String? title;
  String? discountType;
  String? discountValue;
  int? inclVatFeePrice;
  int? exclVatFeePrice;
  int? order;
  int? endTime;
  bool? theShow;

  ResponseSearchedRoomDataShowPricesPromotion({
    this.title,
    this.discountType,
    this.discountValue,
    this.inclVatFeePrice,
    this.exclVatFeePrice,
    this.order,
    this.endTime,
    this.theShow,
  });
  ResponseSearchedRoomDataShowPricesPromotion.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    discountType = json['discount_type']?.toString();
    discountValue = json['discount_value']?.toString();
    inclVatFeePrice = json['incl_vat_fee_price']?.toInt();
    exclVatFeePrice = json['excl_vat_fee_price']?.toInt();
    order = json['order']?.toInt();
    endTime = json['end_time']?.toInt();
    theShow = json['show'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['discount_type'] = discountType;
    data['discount_value'] = discountValue;
    data['incl_vat_fee_price'] = inclVatFeePrice;
    data['excl_vat_fee_price'] = exclVatFeePrice;
    data['order'] = order;
    data['end_time'] = endTime;
    data['show'] = theShow;
    return data;
  }
}

class ResponseSearchedRoomDataShowPrices {
/*
{
  "promotion": {
    "title": "",
    "discount_type": "",
    "discount_value": "",
    "incl_vat_fee_price": 0,
    "excl_vat_fee_price": 0,
    "order": 1,
    "end_time": -1,
    "show": false
  },
  "member_discount": {
    "title": "SECRET_DEALS",
    "discount_type": "",
    "discount_value": "",
    "incl_vat_fee_price": 0,
    "excl_vat_fee_price": 0,
    "order": 2,
    "show": false
  },
  "mobile_rate": {
    "title": "MOBILE_RATE",
    "discount_type": "",
    "discount_value": "",
    "incl_vat_fee_price": 0,
    "excl_vat_fee_price": 0,
    "order": 3,
    "show": false
  },
  "loyalty_discount": {
    "title": "",
    "discount_type": "",
    "discount_value": "",
    "incl_vat_fee_price": 0,
    "excl_vat_fee_price": 0,
    "order": 4,
    "show": false
  },
  "discount_coupon": {
    "title": "",
    "discount_type": "",
    "discount_value": "",
    "incl_vat_fee_price": 0,
    "excl_vat_fee_price": 0,
    "order": 5,
    "show": false
  },
  "final_price": {
    "title": "Giá cuối",
    "discount_type": "PERCENT",
    "incl_discount_value": 0,
    "excl_discount_value": 0,
    "incl_vat_fee_price": 360000,
    "excl_vat_fee_price": 342000,
    "order": 6,
    "show": false
  }
}
*/

  ResponseSearchedRoomDataShowPricesPromotion? promotion;
  ResponseSearchedRoomDataShowPricesMemberDiscount? memberDiscount;
  ResponseSearchedRoomDataShowPricesMobileRate? mobileRate;
  ResponseSearchedRoomDataShowPricesLoyaltyDiscount? loyaltyDiscount;
  ResponseSearchedRoomDataShowPricesDiscountCoupon? discountCoupon;
  ResponseSearchedRoomDataShowPricesFinalPrice? finalPrice;

  ResponseSearchedRoomDataShowPrices({
    this.promotion,
    this.memberDiscount,
    this.mobileRate,
    this.loyaltyDiscount,
    this.discountCoupon,
    this.finalPrice,
  });
  ResponseSearchedRoomDataShowPrices.fromJson(Map<String, dynamic> json) {
    promotion = (json['promotion'] != null) ? ResponseSearchedRoomDataShowPricesPromotion.fromJson(json['promotion']) : null;
    memberDiscount = (json['member_discount'] != null) ? ResponseSearchedRoomDataShowPricesMemberDiscount.fromJson(json['member_discount']) : null;
    mobileRate = (json['mobile_rate'] != null) ? ResponseSearchedRoomDataShowPricesMobileRate.fromJson(json['mobile_rate']) : null;
    loyaltyDiscount = (json['loyalty_discount'] != null) ? ResponseSearchedRoomDataShowPricesLoyaltyDiscount.fromJson(json['loyalty_discount']) : null;
    discountCoupon = (json['discount_coupon'] != null) ? ResponseSearchedRoomDataShowPricesDiscountCoupon.fromJson(json['discount_coupon']) : null;
    finalPrice = (json['final_price'] != null) ? ResponseSearchedRoomDataShowPricesFinalPrice.fromJson(json['final_price']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (promotion != null) {
      data['promotion'] = promotion!.toJson();
    }
    if (memberDiscount != null) {
      data['member_discount'] = memberDiscount!.toJson();
    }
    if (mobileRate != null) {
      data['mobile_rate'] = mobileRate!.toJson();
    }
    if (loyaltyDiscount != null) {
      data['loyalty_discount'] = loyaltyDiscount!.toJson();
    }
    if (discountCoupon != null) {
      data['discount_coupon'] = discountCoupon!.toJson();
    }
    if (finalPrice != null) {
      data['final_price'] = finalPrice!.toJson();
    }
    return data;
  }
}

class ResponseSearchedRoomDataGroupFacilities {
/*
{
  "group_name": "Chỗ đỗ xe",
  "id": 54,
  "group_order": 1,
  "key": "parking"
}
*/

  String? groupName;
  int? id;
  int? groupOrder;
  String? key;

  ResponseSearchedRoomDataGroupFacilities({
    this.groupName,
    this.id,
    this.groupOrder,
    this.key,
  });
  ResponseSearchedRoomDataGroupFacilities.fromJson(Map<String, dynamic> json) {
    groupName = json['group_name']?.toString();
    id = json['id']?.toInt();
    groupOrder = json['group_order']?.toInt();
    key = json['key']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['group_name'] = groupName;
    data['id'] = id;
    data['group_order'] = groupOrder;
    data['key'] = key;
    return data;
  }
}

class ResponseSearchedRoomDataLocation {
/*
{
  "lat": 21.0562781,
  "lon": 105.8363472
}
*/

  double? lat;
  double? lon;

  ResponseSearchedRoomDataLocation({
    this.lat,
    this.lon,
  });
  ResponseSearchedRoomDataLocation.fromJson(Map<String, dynamic> json) {
    lat = json['lat']?.toDouble();
    lon = json['lon']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['lat'] = lat;
    data['lon'] = lon;
    return data;
  }
}

class ResponseSearchedRoomData {
/*
{
  "vntrip_id": 10122,
  "provider": "vntrip",
  "checkin_date": "20220826",
  "nights": 1,
  "rooms_available": 36,
  "price": 360000,
  "min_price": 360000,
  "net_price": 342000,
  "rate_id": 23996,
  "rate_type": "ota_rate",
  "rate_code": "",
  "vat": null,
  "included_service_fee": 5,
  "id": 10122,
  "name": "The Royal Hotel",
  "name_vi": "The Royal Hotel",
  "full_address": "60 Nghi Tàm, Phường Yên Phụ, Quận Tây Hồ, Hà Nội",
  "province_id": 66,
  "city_id": 713,
  "star_rate": 3,
  "type": "hotel",
  "active_status": true,
  "status": 1,
  "close_open_status": true,
  "discount_active": true,
  "location": {
    "lat": 21.0562781,
    "lon": 105.8363472
  },
  "free_shuttle": false,
  "full_address_en": "60 Nghi Tam, Yen Phu Ward, Tay Ho District, Ha Noi",
  "groupFacilities": [
    {
      "group_name": "Chỗ đỗ xe",
      "id": 54,
      "group_order": 1,
      "key": "parking"
    }
  ],
  "ranking_score": 202.88,
  "review_point": 7.9,
  "count_reviews": 3,
  "thumb_image": "10122_1499421619_98243080.jpg",
  "show_available": true,
  "bkcom_vat": false,
  "price_one_night": 360000,
  "show_prices": {
    "promotion": {
      "title": "",
      "discount_type": "",
      "discount_value": "",
      "incl_vat_fee_price": 0,
      "excl_vat_fee_price": 0,
      "order": 1,
      "end_time": -1,
      "show": false
    },
    "member_discount": {
      "title": "SECRET_DEALS",
      "discount_type": "",
      "discount_value": "",
      "incl_vat_fee_price": 0,
      "excl_vat_fee_price": 0,
      "order": 2,
      "show": false
    },
    "mobile_rate": {
      "title": "MOBILE_RATE",
      "discount_type": "",
      "discount_value": "",
      "incl_vat_fee_price": 0,
      "excl_vat_fee_price": 0,
      "order": 3,
      "show": false
    },
    "loyalty_discount": {
      "title": "",
      "discount_type": "",
      "discount_value": "",
      "incl_vat_fee_price": 0,
      "excl_vat_fee_price": 0,
      "order": 4,
      "show": false
    },
    "discount_coupon": {
      "title": "",
      "discount_type": "",
      "discount_value": "",
      "incl_vat_fee_price": 0,
      "excl_vat_fee_price": 0,
      "order": 5,
      "show": false
    },
    "final_price": {
      "title": "Giá cuối",
      "discount_type": "PERCENT",
      "incl_discount_value": 0,
      "excl_discount_value": 0,
      "incl_vat_fee_price": 360000,
      "excl_vat_fee_price": 342000,
      "order": 6,
      "show": false
    }
  },
  "mapping_providers": [
    "vntrip"
  ],
  "tags": [
    "has-360img"
  ],
  "have_360img": true,
  "is_special": true,
  "tms_special_hotel_policy": null,
  "is_tms_special_hotel": true
}
*/

  int? vntripId;
  String? provider;
  String? checkinDate;
  int? nights;
  int? roomsAvailable;
  int? price;
  int? minPrice;
  int? netPrice;
  int? rateId;
  String? rateType;
  String? rateCode;
  String? vat;
  int? includedServiceFee;
  int? id;
  String? name;
  String? nameVi;
  String? fullAddress;
  int? provinceId;
  int? cityId;
  dynamic? starRate;
  String? type;
  bool? activeStatus;
  int? status;
  bool? closeOpenStatus;
  bool? discountActive;
  ResponseSearchedRoomDataLocation? location;
  bool? freeShuttle;
  String? fullAddressEn;
  List<ResponseSearchedRoomDataGroupFacilities?>? groupFacilities;
  double? rankingScore;
  double? reviewPoint;
  int? countReviews;
  String? thumbImage;
  bool? showAvailable;
  bool? bkcomVat;
  int? priceOneNight;
  ResponseSearchedRoomDataShowPrices? showPrices;
  List<String?>? mappingProviders;
  List<String?>? tags;
  bool? have_360img;
  bool? isSpecial;
  String? tmsSpecialHotelPolicy;
  bool? isTmsSpecialHotel;

  ResponseSearchedRoomData({
    this.vntripId,
    this.provider,
    this.checkinDate,
    this.nights,
    this.roomsAvailable,
    this.price,
    this.minPrice,
    this.netPrice,
    this.rateId,
    this.rateType,
    this.rateCode,
    this.vat,
    this.includedServiceFee,
    this.id,
    this.name,
    this.nameVi,
    this.fullAddress,
    this.provinceId,
    this.cityId,
    this.starRate,
    this.type,
    this.activeStatus,
    this.status,
    this.closeOpenStatus,
    this.discountActive,
    this.location,
    this.freeShuttle,
    this.fullAddressEn,
    this.groupFacilities,
    this.rankingScore,
    this.reviewPoint,
    this.countReviews,
    this.thumbImage,
    this.showAvailable,
    this.bkcomVat,
    this.priceOneNight,
    this.showPrices,
    this.mappingProviders,
    this.tags,
    this.have_360img,
    this.isSpecial,
    this.tmsSpecialHotelPolicy,
    this.isTmsSpecialHotel,
  });
  ResponseSearchedRoomData.fromJson(Map<String, dynamic> json) {
    vntripId = json['vntrip_id']?.toInt();
    provider = json['provider']?.toString();
    checkinDate = json['checkin_date']?.toString();
    nights = json['nights']?.toInt();
    roomsAvailable = json['rooms_available']?.toInt();
    price = json['price']?.toInt();
    minPrice = json['min_price']?.toInt();
    netPrice = json['net_price']?.toInt();
    rateId = json['rate_id']?.toInt();
    rateType = json['rate_type']?.toString();
    rateCode = json['rate_code']?.toString();
    vat = json['vat']?.toString();
    includedServiceFee = json['included_service_fee']?.toInt();
    id = json['id']?.toInt();
    name = json['name']?.toString();
    nameVi = json['name_vi']?.toString();
    fullAddress = json['full_address']?.toString();
    provinceId = json['province_id']?.toInt();
    cityId = json['city_id']?.toInt();
    starRate = json['star_rate']?.toString();
    type = json['type']?.toString();
    activeStatus = json['active_status'];
    status = json['status']?.toInt();
    closeOpenStatus = json['close_open_status'];
    discountActive = json['discount_active'];
    location = (json['location'] != null) ? ResponseSearchedRoomDataLocation.fromJson(json['location']) : null;
    freeShuttle = json['free_shuttle'];
    fullAddressEn = json['full_address_en']?.toString();
    if (json['groupFacilities'] != null) {
      final v = json['groupFacilities'];
      final arr0 = <ResponseSearchedRoomDataGroupFacilities>[];
      v.forEach((v) {
        arr0.add(ResponseSearchedRoomDataGroupFacilities.fromJson(v));
      });
      groupFacilities = arr0;
    }
    rankingScore = json['ranking_score']?.toDouble();
    reviewPoint = json['review_point']?.toDouble();
    countReviews = json['count_reviews']?.toInt();
    thumbImage = json['thumb_image']?.toString();
    showAvailable = json['show_available'];
    bkcomVat = json['bkcom_vat'];
    priceOneNight = json['price_one_night']?.toInt();
    showPrices = (json['show_prices'] != null) ? ResponseSearchedRoomDataShowPrices.fromJson(json['show_prices']) : null;
    if (json['mapping_providers'] != null) {
      final v = json['mapping_providers'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      mappingProviders = arr0;
    }
    if (json['tags'] != null) {
      final v = json['tags'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      tags = arr0;
    }
    have_360img = json['have_360img'];
    isSpecial = json['is_special'];
    tmsSpecialHotelPolicy = json['tms_special_hotel_policy']?.toString();
    isTmsSpecialHotel = json['is_tms_special_hotel'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['vntrip_id'] = vntripId;
    data['provider'] = provider;
    data['checkin_date'] = checkinDate;
    data['nights'] = nights;
    data['rooms_available'] = roomsAvailable;
    data['price'] = price;
    data['min_price'] = minPrice;
    data['net_price'] = netPrice;
    data['rate_id'] = rateId;
    data['rate_type'] = rateType;
    data['rate_code'] = rateCode;
    data['vat'] = vat;
    data['included_service_fee'] = includedServiceFee;
    data['id'] = id;
    data['name'] = name;
    data['name_vi'] = nameVi;
    data['full_address'] = fullAddress;
    data['province_id'] = provinceId;
    data['city_id'] = cityId;
    data['star_rate'] = starRate;
    data['type'] = type;
    data['active_status'] = activeStatus;
    data['status'] = status;
    data['close_open_status'] = closeOpenStatus;
    data['discount_active'] = discountActive;
    if (location != null) {
      data['location'] = location!.toJson();
    }
    data['free_shuttle'] = freeShuttle;
    data['full_address_en'] = fullAddressEn;
    if (groupFacilities != null) {
      final v = groupFacilities;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['groupFacilities'] = arr0;
    }
    data['ranking_score'] = rankingScore;
    data['review_point'] = reviewPoint;
    data['count_reviews'] = countReviews;
    data['thumb_image'] = thumbImage;
    data['show_available'] = showAvailable;
    data['bkcom_vat'] = bkcomVat;
    data['price_one_night'] = priceOneNight;
    if (showPrices != null) {
      data['show_prices'] = showPrices!.toJson();
    }
    if (mappingProviders != null) {
      final v = mappingProviders;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['mapping_providers'] = arr0;
    }
    if (tags != null) {
      final v = tags;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['tags'] = arr0;
    }
    data['have_360img'] = have_360img;
    data['is_special'] = isSpecial;
    data['tms_special_hotel_policy'] = tmsSpecialHotelPolicy;
    data['is_tms_special_hotel'] = isTmsSpecialHotel;
    return data;
  }

  @override
  String toString() {
    String facilities = '';
    if (groupFacilities!.isNotEmpty) {
      for (var item in groupFacilities!) {
        facilities  = '$facilities , ${item?.groupName}';
      }
    }
    return "$vntripId, $checkinDate, $netPrice, $fullAddress, $nameVi, $provinceId, $facilities, $type ";
  }
}

class ResponseSearchedRoom {
/*
{
  "searchId": "824fc7a98c14170d6f2cd6b9bc591e7dc746c668cc2fd6d9abcda0db841a304e",
  "status": "success",
  "page": 1,
  "limit": 40,
  "total": 16,
  "total_pages": 1,
  "data": [
    {
      "vntrip_id": 10122,
      "provider": "vntrip",
      "checkin_date": "20220826",
      "nights": 1,
      "rooms_available": 36,
      "price": 360000,
      "min_price": 360000,
      "net_price": 342000,
      "rate_id": 23996,
      "rate_type": "ota_rate",
      "rate_code": "",
      "vat": null,
      "included_service_fee": 5,
      "id": 10122,
      "name": "The Royal Hotel",
      "name_vi": "The Royal Hotel",
      "full_address": "60 Nghi Tàm, Phường Yên Phụ, Quận Tây Hồ, Hà Nội",
      "province_id": 66,
      "city_id": 713,
      "star_rate": 3,
      "type": "hotel",
      "active_status": true,
      "status": 1,
      "close_open_status": true,
      "discount_active": true,
      "location": {
        "lat": 21.0562781,
        "lon": 105.8363472
      },
      "free_shuttle": false,
      "full_address_en": "60 Nghi Tam, Yen Phu Ward, Tay Ho District, Ha Noi",
      "groupFacilities": [
        {
          "group_name": "Chỗ đỗ xe",
          "id": 54,
          "group_order": 1,
          "key": "parking"
        }
      ],
      "ranking_score": 202.88,
      "review_point": 7.9,
      "count_reviews": 3,
      "thumb_image": "10122_1499421619_98243080.jpg",
      "show_available": true,
      "bkcom_vat": false,
      "price_one_night": 360000,
      "show_prices": {
        "promotion": {
          "title": "",
          "discount_type": "",
          "discount_value": "",
          "incl_vat_fee_price": 0,
          "excl_vat_fee_price": 0,
          "order": 1,
          "end_time": -1,
          "show": false
        },
        "member_discount": {
          "title": "SECRET_DEALS",
          "discount_type": "",
          "discount_value": "",
          "incl_vat_fee_price": 0,
          "excl_vat_fee_price": 0,
          "order": 2,
          "show": false
        },
        "mobile_rate": {
          "title": "MOBILE_RATE",
          "discount_type": "",
          "discount_value": "",
          "incl_vat_fee_price": 0,
          "excl_vat_fee_price": 0,
          "order": 3,
          "show": false
        },
        "loyalty_discount": {
          "title": "",
          "discount_type": "",
          "discount_value": "",
          "incl_vat_fee_price": 0,
          "excl_vat_fee_price": 0,
          "order": 4,
          "show": false
        },
        "discount_coupon": {
          "title": "",
          "discount_type": "",
          "discount_value": "",
          "incl_vat_fee_price": 0,
          "excl_vat_fee_price": 0,
          "order": 5,
          "show": false
        },
        "final_price": {
          "title": "Giá cuối",
          "discount_type": "PERCENT",
          "incl_discount_value": 0,
          "excl_discount_value": 0,
          "incl_vat_fee_price": 360000,
          "excl_vat_fee_price": 342000,
          "order": 6,
          "show": false
        }
      },
      "mapping_providers": [
        "vntrip"
      ],
      "tags": [
        "has-360img"
      ],
      "have_360img": true,
      "is_special": true,
      "tms_special_hotel_policy": null,
      "is_tms_special_hotel": true
    }
  ],
  "ext_data": {
    "location_info": {
      "province_id": 66,
      "province_name": "Hà Nội",
      "full_addr": "Hà Nội"
    },
    "count_by_price_range": {
      "below_500k": 3,
      "from_500k_to_1m": 12,
      "from_1m_to_2m": 1,
      "from_2m_to_5m": 0,
      "more_than_5m": 0
    },
    "count_by_star": {
      "no_star": 2,
      "one_star": 1,
      "two_star": 4,
      "three_star": 5,
      "four_star": 2,
      "five_star": 2
    },
    "count_by_area": [
      {
        "seo_code": "pho-co-ha-noi",
        "name": "Phố cổ Hà Nội",
        "id": 1,
        "count": 2
      }
    ],
    "count_by_facilities": [
      {
        "seo_code": "ho-boi",
        "name": "Hồ bơi",
        "id": 1,
        "count": 1
      }
    ],
    "count_by_cities": [
      {
        "count": 3,
        "seo_url": "ha-noi/ba-dinh",
        "province_id": 66,
        "city_seo_url": "ba-dinh",
        "name": "Quận Ba Đình",
        "id": 711,
        "province_code": "ha-noi",
        "province_name": "Hà Nội"
      }
    ],
    "count_by_provinces": [
      {
        "count": 16
      }
    ],
    "count_by_type": [
      {
        "count": 16,
        "type": "hotel"
      }
    ],
    "default_location": 0,
    "min_price_all": 80100,
    "max_price_all": 1200000,
    "median_price": 557500
  }
}
*/

  String? searchId;
  String? status;
  int? page;
  int? limit;
  int? total;
  int? totalPages;
  List<ResponseSearchedRoomData?>? data;
  ResponseSearchedRoomExtData? extData;

  ResponseSearchedRoom({
    this.searchId,
    this.status,
    this.page,
    this.limit,
    this.total,
    this.totalPages,
    this.data,
    this.extData,
  });
  ResponseSearchedRoom.fromJson(Map<String, dynamic> json) {
    searchId = json['searchId']?.toString();
    status = json['status']?.toString();
    page = json['page']?.toInt();
    limit = json['limit']?.toInt();
    total = json['total']?.toInt();
    totalPages = json['total_pages']?.toInt();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ResponseSearchedRoomData>[];
      v.forEach((v) {
        arr0.add(ResponseSearchedRoomData.fromJson(v));
      });
      this.data = arr0;
    }
    extData = (json['ext_data'] != null) ? ResponseSearchedRoomExtData.fromJson(json['ext_data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['searchId'] = searchId;
    data['status'] = status;
    data['page'] = page;
    data['limit'] = limit;
    data['total'] = total;
    data['total_pages'] = totalPages;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (extData != null) {
      data['ext_data'] = extData!.toJson();
    }
    return data;
  }
}
