///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ResponseOrderHotelDataOrderDataAccountData {
/*
{
  "account_type": "person"
}
*/

  String? accountType;

  ResponseOrderHotelDataOrderDataAccountData({
    this.accountType,
  });
  ResponseOrderHotelDataOrderDataAccountData.fromJson(Map<String, dynamic> json) {
    accountType = json['account_type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['account_type'] = accountType;
    return data;
  }
}

class ResponseOrderHotelDataOrderDataExtraCustomerData {
/*
{
  "type": "person",
  "email": "tan@gmail.com",
  "phone": "344850761",
  "gender": 2,
  "user_id": 436664,
  "language": "vi",
  "device_id": "d487bf8fc41f7ea6",
  "last_name": "Bùi",
  "first_name": "Chiên"
}
*/

  String? type;
  String? email;
  String? phone;
  int? gender;
  int? userId;
  String? language;
  String? deviceId;
  String? lastName;
  String? firstName;

  ResponseOrderHotelDataOrderDataExtraCustomerData({
    this.type,
    this.email,
    this.phone,
    this.gender,
    this.userId,
    this.language,
    this.deviceId,
    this.lastName,
    this.firstName,
  });
  ResponseOrderHotelDataOrderDataExtraCustomerData.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    email = json['email']?.toString();
    phone = json['phone']?.toString();
    gender = json['gender']?.toInt();
    userId = json['user_id']?.toInt();
    language = json['language']?.toString();
    deviceId = json['device_id']?.toString();
    lastName = json['last_name']?.toString();
    firstName = json['first_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    data['email'] = email;
    data['phone'] = phone;
    data['gender'] = gender;
    data['user_id'] = userId;
    data['language'] = language;
    data['device_id'] = deviceId;
    data['last_name'] = lastName;
    data['first_name'] = firstName;
    return data;
  }
}

class ResponseOrderHotelDataOrderData {
/*
{
  "updated_at": "2022-09-14T05:54:04.352Z",
  "created_at": "2022-09-14T05:54:04.352Z",
  "is_hidden": false,
  "is_closed": false,
  "replaced_times": 0,
  "hold_status": null,
  "id": 957936,
  "order_type": "hotel",
  "request_from": "APP_ANDROID",
  "order_code": "VNTRIP2022S7N2O",
  "order_status": "order_pending_payment",
  "payment_method": "payment_method_inland_123pay",
  "currency": null,
  "customer_request": null,
  "handler_id": null,
  "business_account_id": null,
  "extra_customer_data": {
    "type": "person",
    "email": "tan@gmail.com",
    "phone": "344850761",
    "gender": 2,
    "user_id": 436664,
    "language": "vi",
    "device_id": "d487bf8fc41f7ea6",
    "last_name": "Bùi",
    "first_name": "Chiên"
  },
  "customer_id": 436664,
  "account_data": {
    "account_type": "person"
  },
  "booking_request_id": "2485e7ad-9d7b-4328-966e-d79294116e50",
  "other_expense": [
    null
  ],
  "other_expense_price": 0,
  "extra_rate": [
    null
  ],
  "extra_rate_price": 0,
  "payment_links": [
    null
  ],
  "created_by": null,
  "booking_request_code": "BR-20220914-24227068",
  "publisher_data": null,
  "suggestion_customer_request": "",
  "related_order": null,
  "deal_id": null,
  "deal_options": null,
  "bank_code": null,
  "suggestion_id": [
    "0b3e0bdc-4aa6-4e5e-a0e0-258bda04fc35"
  ],
  "ip_address": "118.70.118.215",
  "trip_voucher": null,
  "trip_business_id": null,
  "hold_expired_time": "2022-09-15T05:54:04.357Z",
  "use_wallet": false,
  "wallet_amount": 0,
  "updated_by": null,
  "extra_data": null,
  "order_success_at": null,
  "order_fail_at": null,
  "order_canceled_at": null,
  "is_confirmed": null,
  "confirmed_at": null,
  "total_price": null,
  "final_price": null,
  "shutter_request": null,
  "tax_request": null,
  "confirmation_data": null,
  "approved_by": null,
  "other_expense_source": null,
  "bank_transfer_info": null
}
*/

  String? updatedAt;
  String? createdAt;
  bool? isHidden;
  bool? isClosed;
  int? replacedTimes;
  String? holdStatus;
  int? id;
  String? orderType;
  String? requestFrom;
  String? orderCode;
  String? orderStatus;
  String? paymentMethod;
  String? currency;
  String? customerRequest;
  String? handlerId;
  String? businessAccountId;
  ResponseOrderHotelDataOrderDataExtraCustomerData? extraCustomerData;
  int? customerId;
  ResponseOrderHotelDataOrderDataAccountData? accountData;
  String? bookingRequestId;
  // List<ResponseOrderHotelDataOrderDataOtherExpense?>? otherExpense;
  int? otherExpensePrice;
  // List<ResponseOrderHotelDataOrderDataExtraRate?>? extraRate;
  int? extraRatePrice;
  // List<ResponseOrderHotelDataOrderDataPaymentLinks?>? paymentLinks;
  String? createdBy;
  String? bookingRequestCode;
  String? publisherData;
  String? suggestionCustomerRequest;
  String? relatedOrder;
  String? dealId;
  String? dealOptions;
  String? bankCode;
  List<String?>? suggestionId;
  String? ipAddress;
  String? tripVoucher;
  String? tripBusinessId;
  String? holdExpiredTime;
  bool? useWallet;
  int? walletAmount;
  String? updatedBy;
  String? extraData;
  String? orderSuccessAt;
  String? orderFailAt;
  String? orderCanceledAt;
  String? isConfirmed;
  String? confirmedAt;
  String? totalPrice;
  String? finalPrice;
  String? shutterRequest;
  String? taxRequest;
  String? confirmationData;
  String? approvedBy;
  String? otherExpenseSource;
  String? bankTransferInfo;

  ResponseOrderHotelDataOrderData({
    this.updatedAt,
    this.createdAt,
    this.isHidden,
    this.isClosed,
    this.replacedTimes,
    this.holdStatus,
    this.id,
    this.orderType,
    this.requestFrom,
    this.orderCode,
    this.orderStatus,
    this.paymentMethod,
    this.currency,
    this.customerRequest,
    this.handlerId,
    this.businessAccountId,
    this.extraCustomerData,
    this.customerId,
    this.accountData,
    this.bookingRequestId,
    // this.otherExpense,
    this.otherExpensePrice,
    // this.extraRate,
    this.extraRatePrice,
    // this.paymentLinks,
    this.createdBy,
    this.bookingRequestCode,
    this.publisherData,
    this.suggestionCustomerRequest,
    this.relatedOrder,
    this.dealId,
    this.dealOptions,
    this.bankCode,
    this.suggestionId,
    this.ipAddress,
    this.tripVoucher,
    this.tripBusinessId,
    this.holdExpiredTime,
    this.useWallet,
    this.walletAmount,
    this.updatedBy,
    this.extraData,
    this.orderSuccessAt,
    this.orderFailAt,
    this.orderCanceledAt,
    this.isConfirmed,
    this.confirmedAt,
    this.totalPrice,
    this.finalPrice,
    this.shutterRequest,
    this.taxRequest,
    this.confirmationData,
    this.approvedBy,
    this.otherExpenseSource,
    this.bankTransferInfo,
  });
  ResponseOrderHotelDataOrderData.fromJson(Map<String, dynamic> json) {
    updatedAt = json['updated_at']?.toString();
    createdAt = json['created_at']?.toString();
    isHidden = json['is_hidden'];
    isClosed = json['is_closed'];
    replacedTimes = json['replaced_times']?.toInt();
    holdStatus = json['hold_status']?.toString();
    id = json['id']?.toInt();
    orderType = json['order_type']?.toString();
    requestFrom = json['request_from']?.toString();
    orderCode = json['order_code']?.toString();
    orderStatus = json['order_status']?.toString();
    paymentMethod = json['payment_method']?.toString();
    currency = json['currency']?.toString();
    customerRequest = json['customer_request']?.toString();
    handlerId = json['handler_id']?.toString();
    businessAccountId = json['business_account_id']?.toString();
    extraCustomerData = (json['extra_customer_data'] != null) ? ResponseOrderHotelDataOrderDataExtraCustomerData.fromJson(json['extra_customer_data']) : null;
    customerId = json['customer_id']?.toInt();
    accountData = (json['account_data'] != null) ? ResponseOrderHotelDataOrderDataAccountData.fromJson(json['account_data']) : null;
    bookingRequestId = json['booking_request_id']?.toString();
    otherExpensePrice = json['other_expense_price']?.toInt();
    extraRatePrice = json['extra_rate_price']?.toInt();
    createdBy = json['created_by']?.toString();
    bookingRequestCode = json['booking_request_code']?.toString();
    publisherData = json['publisher_data']?.toString();
    suggestionCustomerRequest = json['suggestion_customer_request']?.toString();
    relatedOrder = json['related_order']?.toString();
    dealId = json['deal_id']?.toString();
    dealOptions = json['deal_options']?.toString();
    bankCode = json['bank_code']?.toString();
    if (json['suggestion_id'] != null) {
    final v = json['suggestion_id'];
    final arr0 = <String>[];
    v.forEach((v) {
    arr0.add(v.toString());
    });
    suggestionId = arr0;
    }
    ipAddress = json['ip_address']?.toString();
    tripVoucher = json['trip_voucher']?.toString();
    tripBusinessId = json['trip_business_id']?.toString();
    holdExpiredTime = json['hold_expired_time']?.toString();
    useWallet = json['use_wallet'];
    walletAmount = json['wallet_amount']?.toInt();
    updatedBy = json['updated_by']?.toString();
    extraData = json['extra_data']?.toString();
    orderSuccessAt = json['order_success_at']?.toString();
    orderFailAt = json['order_fail_at']?.toString();
    orderCanceledAt = json['order_canceled_at']?.toString();
    isConfirmed = json['is_confirmed']?.toString();
    confirmedAt = json['confirmed_at']?.toString();
    totalPrice = json['total_price']?.toString();
    finalPrice = json['final_price']?.toString();
    shutterRequest = json['shutter_request']?.toString();
    taxRequest = json['tax_request']?.toString();
    confirmationData = json['confirmation_data']?.toString();
    approvedBy = json['approved_by']?.toString();
    otherExpenseSource = json['other_expense_source']?.toString();
    bankTransferInfo = json['bank_transfer_info']?.toString();
    }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['updated_at'] = updatedAt;
    data['created_at'] = createdAt;
    data['is_hidden'] = isHidden;
    data['is_closed'] = isClosed;
    data['replaced_times'] = replacedTimes;
    data['hold_status'] = holdStatus;
    data['id'] = id;
    data['order_type'] = orderType;
    data['request_from'] = requestFrom;
    data['order_code'] = orderCode;
    data['order_status'] = orderStatus;
    data['payment_method'] = paymentMethod;
    data['currency'] = currency;
    data['customer_request'] = customerRequest;
    data['handler_id'] = handlerId;
    data['business_account_id'] = businessAccountId;
    if (extraCustomerData != null) {
      data['extra_customer_data'] = extraCustomerData!.toJson();
    }
    data['customer_id'] = customerId;
    if (accountData != null) {
      data['account_data'] = accountData!.toJson();
    }
    data['booking_request_id'] = bookingRequestId;
    data['other_expense_price'] = otherExpensePrice;
    data['extra_rate_price'] = extraRatePrice;
    data['created_by'] = createdBy;
    data['booking_request_code'] = bookingRequestCode;
    data['publisher_data'] = publisherData;
    data['suggestion_customer_request'] = suggestionCustomerRequest;
    data['related_order'] = relatedOrder;
    data['deal_id'] = dealId;
    data['deal_options'] = dealOptions;
    data['bank_code'] = bankCode;
    if (suggestionId != null) {
    final v = suggestionId;
    final arr0 = [];
    v!.forEach((v) {
    arr0.add(v);
    });
    data['suggestion_id'] = arr0;
    }
    data['ip_address'] = ipAddress;
    data['trip_voucher'] = tripVoucher;
    data['trip_business_id'] = tripBusinessId;
    data['hold_expired_time'] = holdExpiredTime;
    data['use_wallet'] = useWallet;
    data['wallet_amount'] = walletAmount;
    data['updated_by'] = updatedBy;
    data['extra_data'] = extraData;
    data['order_success_at'] = orderSuccessAt;
    data['order_fail_at'] = orderFailAt;
    data['order_canceled_at'] = orderCanceledAt;
    data['is_confirmed'] = isConfirmed;
    data['confirmed_at'] = confirmedAt;
    data['total_price'] = totalPrice;
    data['final_price'] = finalPrice;
    data['shutter_request'] = shutterRequest;
    data['tax_request'] = taxRequest;
    data['confirmation_data'] = confirmationData;
    data['approved_by'] = approvedBy;
    data['other_expense_source'] = otherExpenseSource;
    data['bank_transfer_info'] = bankTransferInfo;
    return data;
  }
}

class ResponseOrderHotelData {
/*
{
  "redirect_url": "https://sbgateway.zalopay.vn/openinapp?order=eyJ6cHRyYW5zdG9rZW4iOiIyMjA5MTQwMDAwMDA0NzBYODF1WGlXIiwiYXBwaWQiOjU1OX0",
  "redirect_url_mobile": "https://sbgateway.zalopay.vn/openinapp?order=eyJ6cHRyYW5zdG9rZW4iOiIyMjA5MTQwMDAwMDA0NzBYODF1WGlXIiwiYXBwaWQiOjU1OX0",
  "zptranstoken": "220914000000470X81uXiW",
  "transaction_id": "220914490037501914472450ZALO",
  "app_id": 559,
  "order_data": {
    "updated_at": "2022-09-14T05:54:04.352Z",
    "created_at": "2022-09-14T05:54:04.352Z",
    "is_hidden": false,
    "is_closed": false,
    "replaced_times": 0,
    "hold_status": null,
    "id": 957936,
    "order_type": "hotel",
    "request_from": "APP_ANDROID",
    "order_code": "VNTRIP2022S7N2O",
    "order_status": "order_pending_payment",
    "payment_method": "payment_method_inland_123pay",
    "currency": null,
    "customer_request": null,
    "handler_id": null,
    "business_account_id": null,
    "extra_customer_data": {
      "type": "person",
      "email": "tan@gmail.com",
      "phone": "344850761",
      "gender": 2,
      "user_id": 436664,
      "language": "vi",
      "device_id": "d487bf8fc41f7ea6",
      "last_name": "Bùi",
      "first_name": "Chiên"
    },
    "customer_id": 436664,
    "account_data": {
      "account_type": "person"
    },
    "booking_request_id": "2485e7ad-9d7b-4328-966e-d79294116e50",
    "other_expense": [
      null
    ],
    "other_expense_price": 0,
    "extra_rate": [
      null
    ],
    "extra_rate_price": 0,
    "payment_links": [
      null
    ],
    "created_by": null,
    "booking_request_code": "BR-20220914-24227068",
    "publisher_data": null,
    "suggestion_customer_request": "",
    "related_order": null,
    "deal_id": null,
    "deal_options": null,
    "bank_code": null,
    "suggestion_id": [
      "0b3e0bdc-4aa6-4e5e-a0e0-258bda04fc35"
    ],
    "ip_address": "118.70.118.215",
    "trip_voucher": null,
    "trip_business_id": null,
    "hold_expired_time": "2022-09-15T05:54:04.357Z",
    "use_wallet": false,
    "wallet_amount": 0,
    "updated_by": null,
    "extra_data": null,
    "order_success_at": null,
    "order_fail_at": null,
    "order_canceled_at": null,
    "is_confirmed": null,
    "confirmed_at": null,
    "total_price": null,
    "final_price": null,
    "shutter_request": null,
    "tax_request": null,
    "confirmation_data": null,
    "approved_by": null,
    "other_expense_source": null,
    "bank_transfer_info": null
  }
}
*/

  String? redirectUrl;
  String? redirectUrlMobile;
  String? zptranstoken;
  String? transactionId;
  int? appId;
  ResponseOrderHotelDataOrderData? orderData;

  ResponseOrderHotelData({
    this.redirectUrl,
    this.redirectUrlMobile,
    this.zptranstoken,
    this.transactionId,
    this.appId,
    this.orderData,
  });
  ResponseOrderHotelData.fromJson(Map<String, dynamic> json) {
    redirectUrl = json['redirect_url']?.toString();
    redirectUrlMobile = json['redirect_url_mobile']?.toString();
    zptranstoken = json['zptranstoken']?.toString();
    transactionId = json['transaction_id']?.toString();
    appId = json['app_id']?.toInt();
    orderData = (json['order_data'] != null) ? ResponseOrderHotelDataOrderData.fromJson(json['order_data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['redirect_url'] = redirectUrl;
    data['redirect_url_mobile'] = redirectUrlMobile;
    data['zptranstoken'] = zptranstoken;
    data['transaction_id'] = transactionId;
    data['app_id'] = appId;
    if (orderData != null) {
      data['order_data'] = orderData!.toJson();
    }
    return data;
  }
}

class ResponseOrderHotel {
/*
{
  "status": "success",
  "message": "Success",
  "data": {
    "redirect_url": "https://sbgateway.zalopay.vn/openinapp?order=eyJ6cHRyYW5zdG9rZW4iOiIyMjA5MTQwMDAwMDA0NzBYODF1WGlXIiwiYXBwaWQiOjU1OX0",
    "redirect_url_mobile": "https://sbgateway.zalopay.vn/openinapp?order=eyJ6cHRyYW5zdG9rZW4iOiIyMjA5MTQwMDAwMDA0NzBYODF1WGlXIiwiYXBwaWQiOjU1OX0",
    "zptranstoken": "220914000000470X81uXiW",
    "transaction_id": "220914490037501914472450ZALO",
    "app_id": 559,
    "order_data": {
      "updated_at": "2022-09-14T05:54:04.352Z",
      "created_at": "2022-09-14T05:54:04.352Z",
      "is_hidden": false,
      "is_closed": false,
      "replaced_times": 0,
      "hold_status": null,
      "id": 957936,
      "order_type": "hotel",
      "request_from": "APP_ANDROID",
      "order_code": "VNTRIP2022S7N2O",
      "order_status": "order_pending_payment",
      "payment_method": "payment_method_inland_123pay",
      "currency": null,
      "customer_request": null,
      "handler_id": null,
      "business_account_id": null,
      "extra_customer_data": {
        "type": "person",
        "email": "tan@gmail.com",
        "phone": "344850761",
        "gender": 2,
        "user_id": 436664,
        "language": "vi",
        "device_id": "d487bf8fc41f7ea6",
        "last_name": "Bùi",
        "first_name": "Chiên"
      },
      "customer_id": 436664,
      "account_data": {
        "account_type": "person"
      },
      "booking_request_id": "2485e7ad-9d7b-4328-966e-d79294116e50",
      "other_expense": [
        null
      ],
      "other_expense_price": 0,
      "extra_rate": [
        null
      ],
      "extra_rate_price": 0,
      "payment_links": [
        null
      ],
      "created_by": null,
      "booking_request_code": "BR-20220914-24227068",
      "publisher_data": null,
      "suggestion_customer_request": "",
      "related_order": null,
      "deal_id": null,
      "deal_options": null,
      "bank_code": null,
      "suggestion_id": [
        "0b3e0bdc-4aa6-4e5e-a0e0-258bda04fc35"
      ],
      "ip_address": "118.70.118.215",
      "trip_voucher": null,
      "trip_business_id": null,
      "hold_expired_time": "2022-09-15T05:54:04.357Z",
      "use_wallet": false,
      "wallet_amount": 0,
      "updated_by": null,
      "extra_data": null,
      "order_success_at": null,
      "order_fail_at": null,
      "order_canceled_at": null,
      "is_confirmed": null,
      "confirmed_at": null,
      "total_price": null,
      "final_price": null,
      "shutter_request": null,
      "tax_request": null,
      "confirmation_data": null,
      "approved_by": null,
      "other_expense_source": null,
      "bank_transfer_info": null
    }
  },
  "return_code": 1
}
*/

  String? status;
  String? message;
  ResponseOrderHotelData? data;
  int? returnCode;

  ResponseOrderHotel({
    this.status,
    this.message,
    this.data,
    this.returnCode,
  });
  ResponseOrderHotel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    message = json['message']?.toString();
    data = (json['data'] != null) ? ResponseOrderHotelData.fromJson(json['data']) : null;
    returnCode = json['return_code']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['return_code'] = returnCode;
    return data;
  }
}
