///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ResponseSuggestDataHotelsVntExtData {
/*
{
  "province_id": 69,
  "area_id": 0,
  "type": "hotel",
  "city_id": 775
}
*/

  int? provinceId;
  int? areaId;
  String? type;
  int? cityId;

  ResponseSuggestDataHotelsVntExtData({
    this.provinceId,
    this.areaId,
    this.type,
    this.cityId,
  });
  ResponseSuggestDataHotelsVntExtData.fromJson(Map<String, dynamic> json) {
    provinceId = json['province_id']?.toInt();
    areaId = json['area_id']?.toInt();
    type = json['type']?.toString();
    cityId = json['city_id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['province_id'] = provinceId;
    data['area_id'] = areaId;
    data['type'] = type;
    data['city_id'] = cityId;
    return data;
  }
}

class ResponseSuggestDataHotels {
/*
{
  "starrating": 3,
  "code": "vn-15314",
  "address": "61 Châu Văn Liêm, An Lạc, Ninh Kiều, Cần Thơ, Việt Nam",
  "name_vi": "KHÁCH SẠN TÂY ĐÔ",
  "check_in_time": "14:00:00",
  "countrycode": "VN",
  "latitude": "10.0308740",
  "countryname": "Vietnam",
  "check_out_time": "12:00:00",
  "countryid": 1,
  "active_status": "active",
  "provider": "vntrip",
  "name": "TAY DO HOTEL",
  "address_en": "61 Chau Van Liem, An Lac, Ninh Kieu, Can Tho, Viet Nam",
  "vnt_ext_data": {
    "province_id": 69,
    "area_id": 0,
    "type": "hotel",
    "city_id": 775
  },
  "id": 15314,
  "propertycurrency": "VND",
  "longitude": "105.7857570"
}
*/

  int? starrating;
  String? code;
  String? address;
  String? nameVi;
  String? checkInTime;
  String? countrycode;
  String? latitude;
  String? countryname;
  String? checkOutTime;
  int? countryid;
  String? activeStatus;
  String? provider;
  String? name;
  String? addressEn;
  ResponseSuggestDataHotelsVntExtData? vntExtData;
  int? id;
  String? propertycurrency;
  String? longitude;

  ResponseSuggestDataHotels({
    this.starrating,
    this.code,
    this.address,
    this.nameVi,
    this.checkInTime,
    this.countrycode,
    this.latitude,
    this.countryname,
    this.checkOutTime,
    this.countryid,
    this.activeStatus,
    this.provider,
    this.name,
    this.addressEn,
    this.vntExtData,
    this.id,
    this.propertycurrency,
    this.longitude,
  });
  ResponseSuggestDataHotels.fromJson(Map<String, dynamic> json) {
    starrating = json['starrating']?.toInt();
    code = json['code']?.toString();
    address = json['address']?.toString();
    nameVi = json['name_vi']?.toString();
    checkInTime = json['check_in_time']?.toString();
    countrycode = json['countrycode']?.toString();
    latitude = json['latitude']?.toString();
    countryname = json['countryname']?.toString();
    checkOutTime = json['check_out_time']?.toString();
    countryid = json['countryid']?.toInt();
    activeStatus = json['active_status']?.toString();
    provider = json['provider']?.toString();
    name = json['name']?.toString();
    addressEn = json['address_en']?.toString();
    vntExtData = (json['vnt_ext_data'] != null) ? ResponseSuggestDataHotelsVntExtData.fromJson(json['vnt_ext_data']) : null;
    id = json['id']?.toInt();
    propertycurrency = json['propertycurrency']?.toString();
    longitude = json['longitude']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['starrating'] = starrating;
    data['code'] = code;
    data['address'] = address;
    data['name_vi'] = nameVi;
    data['check_in_time'] = checkInTime;
    data['countrycode'] = countrycode;
    data['latitude'] = latitude;
    data['countryname'] = countryname;
    data['check_out_time'] = checkOutTime;
    data['countryid'] = countryid;
    data['active_status'] = activeStatus;
    data['provider'] = provider;
    data['name'] = name;
    data['address_en'] = addressEn;
    if (vntExtData != null) {
      data['vnt_ext_data'] = vntExtData!.toJson();
    }
    data['id'] = id;
    data['propertycurrency'] = propertycurrency;
    data['longitude'] = longitude;
    return data;
  }
}

class ResponseSuggestDataRegionsAncestors {
/*
{
  "id": 1,
  "type": "country"
}
*/

  int? id;
  String? type;

  ResponseSuggestDataRegionsAncestors({
    this.id,
    this.type,
  });
  ResponseSuggestDataRegionsAncestors.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    type = json['type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['type'] = type;
    return data;
  }
}

class ResponseSuggestDataRegionsLocation {
/*
{
  "lon": 106.0033909,
  "lat": 11.404629
}
*/

  double? lon;
  double? lat;

  ResponseSuggestDataRegionsLocation({
    this.lon,
    this.lat,
  });
  ResponseSuggestDataRegionsLocation.fromJson(Map<String, dynamic> json) {
    lon = json['lon']?.toDouble();
    lat = json['lat']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['lon'] = lon;
    data['lat'] = lat;
    return data;
  }
}

class ResponseSuggestDataRegions {
/*
{
  "regionnamelong": "Tay Ninh, VietNam",
  "seo_url": "tay-ninh",
  "regioncode": "vn-p-106",
  "regiontype": "vntrip province",
  "regionnamelong_vi": "Tây Ninh, Việt Nam",
  "countrycode": "VN",
  "countryname": "Vietnam",
  "number_of_hotels": "19",
  "regionname_vi": "Tây Ninh",
  "regionid": "106",
  "provider": "vntrip",
  "regionname": "Tay Ninh",
  "location": {
    "lon": 106.0033909,
    "lat": 11.404629
  },
  "ancestors": [
    {
      "id": 1,
      "type": "country"
    }
  ],
  "region": "domestic",
  "score": 4170
}
*/

  String? regionnamelong;
  String? seoUrl;
  String? regioncode;
  String? regiontype;
  String? regionnamelongVi;
  String? countrycode;
  String? countryname;
  String? numberOfHotels;
  String? regionnameVi;
  String? regionid;
  String? provider;
  String? regionname;
  ResponseSuggestDataRegionsLocation? location;
  List<ResponseSuggestDataRegionsAncestors?>? ancestors;
  String? region;
  int? score;

  ResponseSuggestDataRegions({
    this.regionnamelong,
    this.seoUrl,
    this.regioncode,
    this.regiontype,
    this.regionnamelongVi,
    this.countrycode,
    this.countryname,
    this.numberOfHotels,
    this.regionnameVi,
    this.regionid,
    this.provider,
    this.regionname,
    this.location,
    this.ancestors,
    this.region,
    this.score,
  });
  ResponseSuggestDataRegions.fromJson(Map<String, dynamic> json) {
    regionnamelong = json['regionnamelong']?.toString();
    seoUrl = json['seo_url']?.toString();
    regioncode = json['regioncode']?.toString();
    regiontype = json['regiontype']?.toString();
    regionnamelongVi = json['regionnamelong_vi']?.toString();
    countrycode = json['countrycode']?.toString();
    countryname = json['countryname']?.toString();
    numberOfHotels = json['number_of_hotels']?.toString();
    regionnameVi = json['regionname_vi']?.toString();
    regionid = json['regionid']?.toString();
    provider = json['provider']?.toString();
    regionname = json['regionname']?.toString();
    location = (json['location'] != null) ? ResponseSuggestDataRegionsLocation.fromJson(json['location']) : null;
    if (json['ancestors'] != null) {
      final v = json['ancestors'];
      final arr0 = <ResponseSuggestDataRegionsAncestors>[];
      v.forEach((v) {
        arr0.add(ResponseSuggestDataRegionsAncestors.fromJson(v));
      });
      ancestors = arr0;
    }
    region = json['region']?.toString();
    score = json['score']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['regionnamelong'] = regionnamelong;
    data['seo_url'] = seoUrl;
    data['regioncode'] = regioncode;
    data['regiontype'] = regiontype;
    data['regionnamelong_vi'] = regionnamelongVi;
    data['countrycode'] = countrycode;
    data['countryname'] = countryname;
    data['number_of_hotels'] = numberOfHotels;
    data['regionname_vi'] = regionnameVi;
    data['regionid'] = regionid;
    data['provider'] = provider;
    data['regionname'] = regionname;
    if (location != null) {
      data['location'] = location!.toJson();
    }
    if (ancestors != null) {
      final v = ancestors;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['ancestors'] = arr0;
    }
    data['region'] = region;
    data['score'] = score;
    return data;
  }
}

class ResponseSuggestData {
/*
{
  "regions": [
    {
      "regionnamelong": "Tay Ninh, VietNam",
      "seo_url": "tay-ninh",
      "regioncode": "vn-p-106",
      "regiontype": "vntrip province",
      "regionnamelong_vi": "Tây Ninh, Việt Nam",
      "countrycode": "VN",
      "countryname": "Vietnam",
      "number_of_hotels": "19",
      "regionname_vi": "Tây Ninh",
      "regionid": "106",
      "provider": "vntrip",
      "regionname": "Tay Ninh",
      "location": {
        "lon": 106.0033909,
        "lat": 11.404629
      },
      "ancestors": [
        {
          "id": 1,
          "type": "country"
        }
      ],
      "region": "domestic",
      "score": 4170
    }
  ],
  "hotels": [
    {
      "starrating": 3,
      "code": "vn-15314",
      "address": "61 Châu Văn Liêm, An Lạc, Ninh Kiều, Cần Thơ, Việt Nam",
      "name_vi": "KHÁCH SẠN TÂY ĐÔ",
      "check_in_time": "14:00:00",
      "countrycode": "VN",
      "latitude": "10.0308740",
      "countryname": "Vietnam",
      "check_out_time": "12:00:00",
      "countryid": 1,
      "active_status": "active",
      "provider": "vntrip",
      "name": "TAY DO HOTEL",
      "address_en": "61 Chau Van Liem, An Lac, Ninh Kieu, Can Tho, Viet Nam",
      "vnt_ext_data": {
        "province_id": 69,
        "area_id": 0,
        "type": "hotel",
        "city_id": 775
      },
      "id": 15314,
      "propertycurrency": "VND",
      "longitude": "105.7857570"
    }
  ]
}
*/

  List<ResponseSuggestDataRegions?>? regions;
  List<ResponseSuggestDataHotels?>? hotels;

  ResponseSuggestData({
    this.regions,
    this.hotels,
  });
  ResponseSuggestData.fromJson(Map<String, dynamic> json) {
    if (json['regions'] != null) {
      final v = json['regions'];
      final arr0 = <ResponseSuggestDataRegions>[];
      v.forEach((v) {
        arr0.add(ResponseSuggestDataRegions.fromJson(v));
      });
      regions = arr0;
    }
    if (json['hotels'] != null) {
      final v = json['hotels'];
      final arr0 = <ResponseSuggestDataHotels>[];
      v.forEach((v) {
        arr0.add(ResponseSuggestDataHotels.fromJson(v));
      });
      hotels = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (regions != null) {
      final v = regions;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['regions'] = arr0;
    }
    if (hotels != null) {
      final v = hotels;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['hotels'] = arr0;
    }
    return data;
  }
}

class ResponseSuggest {
/*
{
  "status": "success",
  "data": {
    "regions": [
      {
        "regionnamelong": "Tay Ninh, VietNam",
        "seo_url": "tay-ninh",
        "regioncode": "vn-p-106",
        "regiontype": "vntrip province",
        "regionnamelong_vi": "Tây Ninh, Việt Nam",
        "countrycode": "VN",
        "countryname": "Vietnam",
        "number_of_hotels": "19",
        "regionname_vi": "Tây Ninh",
        "regionid": "106",
        "provider": "vntrip",
        "regionname": "Tay Ninh",
        "location": {
          "lon": 106.0033909,
          "lat": 11.404629
        },
        "ancestors": [
          {
            "id": 1,
            "type": "country"
          }
        ],
        "region": "domestic",
        "score": 4170
      }
    ],
    "hotels": [
      {
        "starrating": 3,
        "code": "vn-15314",
        "address": "61 Châu Văn Liêm, An Lạc, Ninh Kiều, Cần Thơ, Việt Nam",
        "name_vi": "KHÁCH SẠN TÂY ĐÔ",
        "check_in_time": "14:00:00",
        "countrycode": "VN",
        "latitude": "10.0308740",
        "countryname": "Vietnam",
        "check_out_time": "12:00:00",
        "countryid": 1,
        "active_status": "active",
        "provider": "vntrip",
        "name": "TAY DO HOTEL",
        "address_en": "61 Chau Van Liem, An Lac, Ninh Kieu, Can Tho, Viet Nam",
        "vnt_ext_data": {
          "province_id": 69,
          "area_id": 0,
          "type": "hotel",
          "city_id": 775
        },
        "id": 15314,
        "propertycurrency": "VND",
        "longitude": "105.7857570"
      }
    ]
  }
}
*/

  String? status;
  ResponseSuggestData? data;

  ResponseSuggest({
    this.status,
    this.data,
  });
  ResponseSuggest.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    data = (json['data'] != null) ? ResponseSuggestData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
