///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ResponseFlightRateData {
/*
{
  "generalTicketId": "0ea92439-33c7-4bea-bd15-32151b13ed84",
  "bookingRequestId": "5a5fba9f-8dd1-4833-aa40-3a97dd8e4084",
  "bookingRequestSuggestionId": "9dbd76f5-ca71-45dc-a7f9-cde8feb7d018",
  "flightRateIds": [
    "79a582cc-911f-47a5-8893-17cb8c264f21"
  ]
}
*/

  String? generalTicketId;
  String? bookingRequestId;
  String? bookingRequestSuggestionId;
  List<String?>? flightRateIds;

  ResponseFlightRateData({
    this.generalTicketId,
    this.bookingRequestId,
    this.bookingRequestSuggestionId,
    this.flightRateIds,
  });
  ResponseFlightRateData.fromJson(Map<String, dynamic> json) {
    generalTicketId = json['generalTicketId']?.toString();
    bookingRequestId = json['bookingRequestId']?.toString();
    bookingRequestSuggestionId = json['bookingRequestSuggestionId']?.toString();
    if (json['flightRateIds'] != null) {
      final v = json['flightRateIds'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      flightRateIds = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['generalTicketId'] = generalTicketId;
    data['bookingRequestId'] = bookingRequestId;
    data['bookingRequestSuggestionId'] = bookingRequestSuggestionId;
    if (flightRateIds != null) {
      final v = flightRateIds;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['flightRateIds'] = arr0;
    }
    return data;
  }
}

class ResponseFlightRate {
/*
{
  "status": 201,
  "message": "Created flight rates!",
  "data": {
    "generalTicketId": "0ea92439-33c7-4bea-bd15-32151b13ed84",
    "bookingRequestId": "5a5fba9f-8dd1-4833-aa40-3a97dd8e4084",
    "bookingRequestSuggestionId": "9dbd76f5-ca71-45dc-a7f9-cde8feb7d018",
    "flightRateIds": [
      "79a582cc-911f-47a5-8893-17cb8c264f21"
    ]
  }
}
*/

  int? status;
  String? message;
  ResponseFlightRateData? data;

  ResponseFlightRate({
    this.status,
    this.message,
    this.data,
  });
  ResponseFlightRate.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    message = json['message']?.toString();
    data = (json['data'] != null) ? ResponseFlightRateData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
