///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoyaltiesData {
/*
{
  "id": "788bbe05-cd59-4b77-92f8-dfc7c88c3cad",
  "program_name_vi": "V-Point",
  "program_name_en": "V-Point",
  "program_url": "vntrip.vn",
  "program_no_of_approvers": 1,
  "program_setting_last_updated_date": "2020-06-19T04:48:01.000Z",
  "activation_requested_by": null,
  "activation_request_date": null,
  "activation_approved_by": null,
  "activation_approval_date": null,
  "pt_eqv_hotel_min": "50000",
  "pt_eqv_hotel_max": null,
  "pt_eqv_flight_min": null,
  "pt_eqv_flight_max": null,
  "point_exchange_rate": null,
  "point_validity": null,
  "point_validity_unit": null,
  "point_allow_extension": null,
  "point_max_add": null,
  "point_add_require_approve": null,
  "point_setting_last_updated_date": null,
  "membership_level_caculated_by": null,
  "membership_validity": null,
  "membership_validity_unit": null,
  "membership_expiry_allows_override": null,
  "membership_level_demote_by": null,
  "membership_allow_extension": null,
  "membership_max_extension": null,
  "membership_max_extension_unit": null,
  "membership_extend_require_approve": null,
  "membership_setting_last_updated": null,
  "is_third_party": true,
  "membership_setting_last_updated_by": null,
  "status": "SUSPENSION_REQUESTED",
  "program_faq_url": "vntrip.vn",
  "program_description_vi": "Chương trình tích điểm Vpoint",
  "program_description_en": "Chương trình tích điểm Vpoint",
  "point_allow_add": null,
  "point_max_extension": null,
  "point_max_extension_unit": null,
  "membership_eligible_booking_months": null,
  "terms_and_conditions": null,
  "point_equivelance_unit": "VND",
  "terms_and_conditions_en": null,
  "allow_reward_split": false,
  "percentage_split": 0,
  "program_image": "20200316_101230_maxresdefault.jpg",
  "program_provider_id": 1,
  "identification_config": "0010010011",
  "limit_reward_allocation": false,
  "allocation_value": null,
  "allocation_has_validity": null,
  "limit_member_reward": "UNLIMITED",
  "member_reward_limit": null,
  "member_limit_period": null,
  "member_limit_period_unit": null,
  "reward_unit": 1,
  "updated_at": "2020-03-16T10:18:10.460Z",
  "created_at": "2018-06-07T10:47:02.842Z",
  "membership_booking_value_period": null,
  "membership_percentage_of_ebv": null,
  "updated_by": 406361,
  "point_expiry_mode": null,
  "supplier": "vpoint"
}
*/

  String? id;
  String? programNameVi;
  String? programNameEn;
  String? programUrl;
  int? programNoOfApprovers;
  String? programSettingLastUpdatedDate;
  String? activationRequestedBy;
  String? activationRequestDate;
  String? activationApprovedBy;
  String? activationApprovalDate;
  String? ptEqvHotelMin;
  String? ptEqvHotelMax;
  String? ptEqvFlightMin;
  String? ptEqvFlightMax;
  String? pointExchangeRate;
  String? pointValidity;
  String? pointValidityUnit;
  String? pointAllowExtension;
  String? pointMaxAdd;
  String? pointAddRequireApprove;
  String? pointSettingLastUpdatedDate;
  String? membershipLevelCaculatedBy;
  String? membershipValidity;
  String? membershipValidityUnit;
  String? membershipExpiryAllowsOverride;
  String? membershipLevelDemoteBy;
  String? membershipAllowExtension;
  String? membershipMaxExtension;
  String? membershipMaxExtensionUnit;
  String? membershipExtendRequireApprove;
  String? membershipSettingLastUpdated;
  bool? isThirdParty;
  String? membershipSettingLastUpdatedBy;
  String? status;
  String? programFaqUrl;
  String? programDescriptionVi;
  String? programDescriptionEn;
  String? pointAllowAdd;
  String? pointMaxExtension;
  String? pointMaxExtensionUnit;
  String? membershipEligibleBookingMonths;
  String? termsAndConditions;
  String? pointEquivelanceUnit;
  String? termsAndConditionsEn;
  bool? allowRewardSplit;
  int? percentageSplit;
  String? programImage;
  int? programProviderId;
  String? identificationConfig;
  bool? limitRewardAllocation;
  String? allocationValue;
  String? allocationHasValidity;
  String? limitMemberReward;
  String? memberRewardLimit;
  String? memberLimitPeriod;
  String? memberLimitPeriodUnit;
  int? rewardUnit;
  String? updatedAt;
  String? createdAt;
  String? membershipBookingValuePeriod;
  String? membershipPercentageOfEbv;
  int? updatedBy;
  String? pointExpiryMode;
  String? supplier;

  LoyaltiesData({
    this.id,
    this.programNameVi,
    this.programNameEn,
    this.programUrl,
    this.programNoOfApprovers,
    this.programSettingLastUpdatedDate,
    this.activationRequestedBy,
    this.activationRequestDate,
    this.activationApprovedBy,
    this.activationApprovalDate,
    this.ptEqvHotelMin,
    this.ptEqvHotelMax,
    this.ptEqvFlightMin,
    this.ptEqvFlightMax,
    this.pointExchangeRate,
    this.pointValidity,
    this.pointValidityUnit,
    this.pointAllowExtension,
    this.pointMaxAdd,
    this.pointAddRequireApprove,
    this.pointSettingLastUpdatedDate,
    this.membershipLevelCaculatedBy,
    this.membershipValidity,
    this.membershipValidityUnit,
    this.membershipExpiryAllowsOverride,
    this.membershipLevelDemoteBy,
    this.membershipAllowExtension,
    this.membershipMaxExtension,
    this.membershipMaxExtensionUnit,
    this.membershipExtendRequireApprove,
    this.membershipSettingLastUpdated,
    this.isThirdParty,
    this.membershipSettingLastUpdatedBy,
    this.status,
    this.programFaqUrl,
    this.programDescriptionVi,
    this.programDescriptionEn,
    this.pointAllowAdd,
    this.pointMaxExtension,
    this.pointMaxExtensionUnit,
    this.membershipEligibleBookingMonths,
    this.termsAndConditions,
    this.pointEquivelanceUnit,
    this.termsAndConditionsEn,
    this.allowRewardSplit,
    this.percentageSplit,
    this.programImage,
    this.programProviderId,
    this.identificationConfig,
    this.limitRewardAllocation,
    this.allocationValue,
    this.allocationHasValidity,
    this.limitMemberReward,
    this.memberRewardLimit,
    this.memberLimitPeriod,
    this.memberLimitPeriodUnit,
    this.rewardUnit,
    this.updatedAt,
    this.createdAt,
    this.membershipBookingValuePeriod,
    this.membershipPercentageOfEbv,
    this.updatedBy,
    this.pointExpiryMode,
    this.supplier,
  });
  LoyaltiesData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    programNameVi = json['program_name_vi']?.toString();
    programNameEn = json['program_name_en']?.toString();
    programUrl = json['program_url']?.toString();
    programNoOfApprovers = json['program_no_of_approvers']?.toInt();
    programSettingLastUpdatedDate = json['program_setting_last_updated_date']?.toString();
    activationRequestedBy = json['activation_requested_by']?.toString();
    activationRequestDate = json['activation_request_date']?.toString();
    activationApprovedBy = json['activation_approved_by']?.toString();
    activationApprovalDate = json['activation_approval_date']?.toString();
    ptEqvHotelMin = json['pt_eqv_hotel_min']?.toString();
    ptEqvHotelMax = json['pt_eqv_hotel_max']?.toString();
    ptEqvFlightMin = json['pt_eqv_flight_min']?.toString();
    ptEqvFlightMax = json['pt_eqv_flight_max']?.toString();
    pointExchangeRate = json['point_exchange_rate']?.toString();
    pointValidity = json['point_validity']?.toString();
    pointValidityUnit = json['point_validity_unit']?.toString();
    pointAllowExtension = json['point_allow_extension']?.toString();
    pointMaxAdd = json['point_max_add']?.toString();
    pointAddRequireApprove = json['point_add_require_approve']?.toString();
    pointSettingLastUpdatedDate = json['point_setting_last_updated_date']?.toString();
    membershipLevelCaculatedBy = json['membership_level_caculated_by']?.toString();
    membershipValidity = json['membership_validity']?.toString();
    membershipValidityUnit = json['membership_validity_unit']?.toString();
    membershipExpiryAllowsOverride = json['membership_expiry_allows_override']?.toString();
    membershipLevelDemoteBy = json['membership_level_demote_by']?.toString();
    membershipAllowExtension = json['membership_allow_extension']?.toString();
    membershipMaxExtension = json['membership_max_extension']?.toString();
    membershipMaxExtensionUnit = json['membership_max_extension_unit']?.toString();
    membershipExtendRequireApprove = json['membership_extend_require_approve']?.toString();
    membershipSettingLastUpdated = json['membership_setting_last_updated']?.toString();
    isThirdParty = json['is_third_party'];
    membershipSettingLastUpdatedBy = json['membership_setting_last_updated_by']?.toString();
    status = json['status']?.toString();
    programFaqUrl = json['program_faq_url']?.toString();
    programDescriptionVi = json['program_description_vi']?.toString();
    programDescriptionEn = json['program_description_en']?.toString();
    pointAllowAdd = json['point_allow_add']?.toString();
    pointMaxExtension = json['point_max_extension']?.toString();
    pointMaxExtensionUnit = json['point_max_extension_unit']?.toString();
    membershipEligibleBookingMonths = json['membership_eligible_booking_months']?.toString();
    termsAndConditions = json['terms_and_conditions']?.toString();
    pointEquivelanceUnit = json['point_equivelance_unit']?.toString();
    termsAndConditionsEn = json['terms_and_conditions_en']?.toString();
    allowRewardSplit = json['allow_reward_split'];
    percentageSplit = json['percentage_split']?.toInt();
    programImage = json['program_image']?.toString();
    programProviderId = json['program_provider_id']?.toInt();
    identificationConfig = json['identification_config']?.toString();
    limitRewardAllocation = json['limit_reward_allocation'];
    allocationValue = json['allocation_value']?.toString();
    allocationHasValidity = json['allocation_has_validity']?.toString();
    limitMemberReward = json['limit_member_reward']?.toString();
    memberRewardLimit = json['member_reward_limit']?.toString();
    memberLimitPeriod = json['member_limit_period']?.toString();
    memberLimitPeriodUnit = json['member_limit_period_unit']?.toString();
    rewardUnit = json['reward_unit']?.toInt();
    updatedAt = json['updated_at']?.toString();
    createdAt = json['created_at']?.toString();
    membershipBookingValuePeriod = json['membership_booking_value_period']?.toString();
    membershipPercentageOfEbv = json['membership_percentage_of_ebv']?.toString();
    updatedBy = json['updated_by']?.toInt();
    pointExpiryMode = json['point_expiry_mode']?.toString();
    supplier = json['supplier']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['program_name_vi'] = programNameVi;
    data['program_name_en'] = programNameEn;
    data['program_url'] = programUrl;
    data['program_no_of_approvers'] = programNoOfApprovers;
    data['program_setting_last_updated_date'] = programSettingLastUpdatedDate;
    data['activation_requested_by'] = activationRequestedBy;
    data['activation_request_date'] = activationRequestDate;
    data['activation_approved_by'] = activationApprovedBy;
    data['activation_approval_date'] = activationApprovalDate;
    data['pt_eqv_hotel_min'] = ptEqvHotelMin;
    data['pt_eqv_hotel_max'] = ptEqvHotelMax;
    data['pt_eqv_flight_min'] = ptEqvFlightMin;
    data['pt_eqv_flight_max'] = ptEqvFlightMax;
    data['point_exchange_rate'] = pointExchangeRate;
    data['point_validity'] = pointValidity;
    data['point_validity_unit'] = pointValidityUnit;
    data['point_allow_extension'] = pointAllowExtension;
    data['point_max_add'] = pointMaxAdd;
    data['point_add_require_approve'] = pointAddRequireApprove;
    data['point_setting_last_updated_date'] = pointSettingLastUpdatedDate;
    data['membership_level_caculated_by'] = membershipLevelCaculatedBy;
    data['membership_validity'] = membershipValidity;
    data['membership_validity_unit'] = membershipValidityUnit;
    data['membership_expiry_allows_override'] = membershipExpiryAllowsOverride;
    data['membership_level_demote_by'] = membershipLevelDemoteBy;
    data['membership_allow_extension'] = membershipAllowExtension;
    data['membership_max_extension'] = membershipMaxExtension;
    data['membership_max_extension_unit'] = membershipMaxExtensionUnit;
    data['membership_extend_require_approve'] = membershipExtendRequireApprove;
    data['membership_setting_last_updated'] = membershipSettingLastUpdated;
    data['is_third_party'] = isThirdParty;
    data['membership_setting_last_updated_by'] = membershipSettingLastUpdatedBy;
    data['status'] = status;
    data['program_faq_url'] = programFaqUrl;
    data['program_description_vi'] = programDescriptionVi;
    data['program_description_en'] = programDescriptionEn;
    data['point_allow_add'] = pointAllowAdd;
    data['point_max_extension'] = pointMaxExtension;
    data['point_max_extension_unit'] = pointMaxExtensionUnit;
    data['membership_eligible_booking_months'] = membershipEligibleBookingMonths;
    data['terms_and_conditions'] = termsAndConditions;
    data['point_equivelance_unit'] = pointEquivelanceUnit;
    data['terms_and_conditions_en'] = termsAndConditionsEn;
    data['allow_reward_split'] = allowRewardSplit;
    data['percentage_split'] = percentageSplit;
    data['program_image'] = programImage;
    data['program_provider_id'] = programProviderId;
    data['identification_config'] = identificationConfig;
    data['limit_reward_allocation'] = limitRewardAllocation;
    data['allocation_value'] = allocationValue;
    data['allocation_has_validity'] = allocationHasValidity;
    data['limit_member_reward'] = limitMemberReward;
    data['member_reward_limit'] = memberRewardLimit;
    data['member_limit_period'] = memberLimitPeriod;
    data['member_limit_period_unit'] = memberLimitPeriodUnit;
    data['reward_unit'] = rewardUnit;
    data['updated_at'] = updatedAt;
    data['created_at'] = createdAt;
    data['membership_booking_value_period'] = membershipBookingValuePeriod;
    data['membership_percentage_of_ebv'] = membershipPercentageOfEbv;
    data['updated_by'] = updatedBy;
    data['point_expiry_mode'] = pointExpiryMode;
    data['supplier'] = supplier;
    return data;
  }
}

class Loyalties {
/*
{
  "status": "success",
  "message": "Success",
  "data": [
    {
      "id": "788bbe05-cd59-4b77-92f8-dfc7c88c3cad",
      "program_name_vi": "V-Point",
      "program_name_en": "V-Point",
      "program_url": "vntrip.vn",
      "program_no_of_approvers": 1,
      "program_setting_last_updated_date": "2020-06-19T04:48:01.000Z",
      "activation_requested_by": null,
      "activation_request_date": null,
      "activation_approved_by": null,
      "activation_approval_date": null,
      "pt_eqv_hotel_min": "50000",
      "pt_eqv_hotel_max": null,
      "pt_eqv_flight_min": null,
      "pt_eqv_flight_max": null,
      "point_exchange_rate": null,
      "point_validity": null,
      "point_validity_unit": null,
      "point_allow_extension": null,
      "point_max_add": null,
      "point_add_require_approve": null,
      "point_setting_last_updated_date": null,
      "membership_level_caculated_by": null,
      "membership_validity": null,
      "membership_validity_unit": null,
      "membership_expiry_allows_override": null,
      "membership_level_demote_by": null,
      "membership_allow_extension": null,
      "membership_max_extension": null,
      "membership_max_extension_unit": null,
      "membership_extend_require_approve": null,
      "membership_setting_last_updated": null,
      "is_third_party": true,
      "membership_setting_last_updated_by": null,
      "status": "SUSPENSION_REQUESTED",
      "program_faq_url": "vntrip.vn",
      "program_description_vi": "Chương trình tích điểm Vpoint",
      "program_description_en": "Chương trình tích điểm Vpoint",
      "point_allow_add": null,
      "point_max_extension": null,
      "point_max_extension_unit": null,
      "membership_eligible_booking_months": null,
      "terms_and_conditions": null,
      "point_equivelance_unit": "VND",
      "terms_and_conditions_en": null,
      "allow_reward_split": false,
      "percentage_split": 0,
      "program_image": "20200316_101230_maxresdefault.jpg",
      "program_provider_id": 1,
      "identification_config": "0010010011",
      "limit_reward_allocation": false,
      "allocation_value": null,
      "allocation_has_validity": null,
      "limit_member_reward": "UNLIMITED",
      "member_reward_limit": null,
      "member_limit_period": null,
      "member_limit_period_unit": null,
      "reward_unit": 1,
      "updated_at": "2020-03-16T10:18:10.460Z",
      "created_at": "2018-06-07T10:47:02.842Z",
      "membership_booking_value_period": null,
      "membership_percentage_of_ebv": null,
      "updated_by": 406361,
      "point_expiry_mode": null,
      "supplier": "vpoint"
    }
  ]
}
*/

  String? status;
  String? message;
  List<LoyaltiesData?>? data;

  Loyalties({
    this.status,
    this.message,
    this.data,
  });
  Loyalties.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <LoyaltiesData>[];
      v.forEach((v) {
        arr0.add(LoyaltiesData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
